### ISSUE TITLE
[Feature] If the last line is code block， cannot add anything after the block

### ISSUE THREAD

**Issue by mrsai** [Milkdown/milkdown#1004]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

If the last line is code block， cannot add anything after the block

### Solution

After the code block is inserted, it is automatically followed by a blank line

### Alternatives

support enter a cursor after a code block

**Comment by Saul-Mirone** [comment]
Use `<Mod + Enter>` to quit it.
