### ISSUE TITLE
[Bug] **字体加粗会渲染为斜体em

### ISSUE THREAD

**Issue by mrsai** [Milkdown/milkdown#1012]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

当前线上的playground

### Steps to reproduce

在 https://milkdown.dev/playground 中。

粗体的渲染会有不同的表现

1.如果输入\*\*然后字符\*\*，会渲染为斜体，继续输入文字，会出现__的内容。
2.如果输入\*\*\*\*然后在第二第三个中间插入入多个文字，会把第一个字符加粗。
3.如果输入\*\* 是的是的 \*\*，文字左右各有一个空格，则没有任何表现，然后再依次删除这俩个空格，字体变为粗体。
4.如果输入\*zifu\*，字符会变斜体
5.如果输入\*\*然后在中间插入入多个文字，会出现“_dd_滴滴”的表现。
7.点击工具栏B，在中文输入法下，输入不会加粗，英文输入法会加粗第一个字符
8.斜体和划线都是同样的问题。

### Expected behavior

输入的顺序会影响输出的结果

### Actual behavior

行为不同输入相同，应该输出相同的结果。

### Runtime

Chrome

### OS

macOS

**Comment by Saul-Mirone** [comment]
Thanks for reporting.
This is already been fixed by https://github.com/Milkdown/milkdown/pull/1011 and will be released within this week.
