### ISSUE TITLE
[Bug] List input strange behavior

### ISSUE THREAD

**Issue by s524797336** [Milkdown/milkdown#1016]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.2.2

### Steps to reproduce

1. Open Milkdown playground.
2. Empty all markdown at right pane
3. Input below markdown to right pane
```
* a
+ b
```
4. Modify left pane casually
5. Look at right pane

### Expected behavior

Generate correct list markdown.

### Actual behavior

Generate  a `<!---->` in markdown between two lists

**Comment by Saul-Mirone** [comment]
The behavior is controlled by [remark](https://github.com/remarkjs/remark). In fact it's a correct behavior. It's used to separate bullet lists to avoid implicit behaviors.
