### ISSUE TITLE
[Bug] 关于图片和链接的解析问题

### ISSUE THREAD

**Issue by mrsai** [Milkdown/milkdown#1027]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.2.3

### Steps to reproduce

在 https://milkdown.dev/playground 中的黏贴链接和图片的表现。

1.黏贴的图片地址会解析为超链接，如我想添加https://milkdown.dev/polar.jpeg这个图片到文档中，我输入![xx](之后黏贴图片地址，会将内容转化为link。

2.如果一个元素是链接，点击会弹出链接的input，多次点击该 input 会报错，该input的值只可以手动修改，如果我在input中黏贴一个新的链接，会直接插入一条新的链接。

### Expected behavior

情况一，如果用户输入的是![xx](表明用户想输入图片，无论后面的路径是否有png等的标识，都应该渲染为图片。如果用户直接黏贴的链接中包含.png,.jpg,,jpeg,webp 等可识别为图片的链接，直接转化为图片。

情况二，如果用户在弹出的input黏贴链接，希望能够直接修改该链接，而不是再插入一条。

**Comment by Saul-Mirone** [comment]
1. The link won't stop you to create the image.

Uploading Screen Recording.mov…

2. The UI is just a demo for link node and is placed in [website](https://github.com/Milkdown/website)'s code base, the milkdown core repo won't provide similar features.

**Comment by mrsai** [comment]
您好，非常感谢您的开源项目！帮到了我很多。
这是我录制的视频。
在输入 " ![xxx](黏贴"   或者 "[xxx](黏贴"  都不是期望的行为。而手动输入这些行为是正常的。
而如果单纯的黏贴，而不输入任何内容，链接的解析是正常的，图片会解析我链接。
[demo](https://github.com/mrsai/vovers/blob/main/QQ20230615-100133.gif)

**Comment by mrsai** [comment]
感谢您的解惑，确实是这样子的情况。我刚才试着把链接黏贴到编辑器之后再次复制出来黏贴居然生成了代码块，可能不同软件对剪切板都有不同的“污染”。最后我黏贴到一个纯文本文档，表现就正常了。

再次感谢！
