### ISSUE TITLE
[Bug] Cannot use commands from the `@milkdown/preset-commonmark`

### ISSUE THREAD

**Issue by zgrybus** [Milkdown/milkdown#1029]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.2.3

### Link to runnable example

https://codesandbox.io/s/smoosh-sunset-ey4uhy?file=/package.json

### Steps to reproduce

**FYI It works in 7.2.2!**

https://github.com/Milkdown/milkdown/assets/17850996/8b2c8aef-3843-44f8-85f7-c47f432d9fe9

1. Go to https://codesandbox.io/s/smoosh-sunset-ey4uhy?file=/package.json
2. Select `Try to strong this text by button above`
3. Click on the `Strong` button
4. Notice that the text has not been bolded, only `**` has been added

### Expected behavior

Text Should be bolded

### Actual behavior

Text is not bolded, only `**` is added

**Comment by healqq** [comment]
Hello @zgrybus!
I encountered this issue again and it seems that it is related to the fact that editor loses focus (as you can notice your button gets focused instead).
I played around a bit and found out that having preventing default event behavior of 'mousedown' event on the button (`event.preventDefault()`) fixes the cursor issue and commands start to work properly. 

Not sure about a11y implications of it, though

**Comment by Sma11X** [comment]
It still have problems even set `event.preventDefault()` on button when selected words start or end with white space.
And I found that if all selected words are white space will cause other problems whether 7.2.2 or 7.2.3
Looks like milkdown transfer white space to '&#x20;'

**Comment by healqq** [comment]
You are right, I was able to reproduce the issue with white space in the playground too: https://milkdown.dev/playground
