### ISSUE TITLE
[Bug] Cannot create table, when there are two instances of the Milkdown

### ISSUE THREAD

**Issue by zgrybus** [Milkdown/milkdown#1030]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.2.3

### Link to runnable example

https://codesandbox.io/s/great-glitter-gycgmm?file=/package.json

### Steps to reproduce

1. Go to https://codesandbox.io/s/great-glitter-gycgmm?file=/package.json
2. Open console
3. Notice that there is an error - `Uncaught Error: Cannot add node 1 because a node with that id is already in the Store.`
4. Click on Table ( first instance )
5. Notice that nothing is happening 

https://github.com/Milkdown/milkdown/assets/17850996/991816d0-f9c1-4fac-a3d5-b4a7de103b6a

### Expected behavior

Table should be created

### Actual behavior

Nothing is happening

I believe, it's related to this:
- https://github.com/Milkdown/milkdown/pull/977
- https://github.com/Milkdown/milkdown/issues/974

**Comment by zgrybus** [comment]
Basically, 
We can't add any command that is `node` 🤔 It seems like blocker :(

**Comment by zgrybus** [comment]
Any news on that @Saul-Mirone?
It's a blocker :(

**Comment by Saul-Mirone** [comment]
Other commands work for me, only the `inertTable` command has bug, I'm still trying to figure it out. If you find other commands also not work, you may call them on the wrong editor instance.

**Comment by zgrybus** [comment]
@Saul-Mirone 
Unfortunately, as I said - it doesn't work for `math`, `diagram` either. They are all commands that use the `node` types.
https://codesandbox.io/s/upbeat-galileo-tskqmp?file=/src/Menu.tsx

**Comment by Saul-Mirone** [comment]
Good catch! Now I know where's the bug.
