### ISSUE TITLE
[Bug] Context "r" not found, do you forget to inject it?

### ISSUE THREAD

**Issue by ningkehua** [Milkdown/milkdown#1036]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.2.0

### Steps to reproduce

I want to set the size of the tab key or space key

### Expected behavior

successfully set, and editor works

### Actual behavior

the console warns that ` Context "r" not found, do you forget to inject it?` , and editor doesn't work

**Comment by ningkehua** [comment]
Here is my code.
When I add settings for indentConfig, an error will be reported

```
  useEditor((root: any) => {
    return Editor.make()
      .config((ctx: any) => {
        ctx.set(rootCtx, root);
        value && ctx.set(defaultValueCtx, value);
        ctx
          .get(listenerCtx)
          .markdownUpdated(
            (ctx: any, markdown: string, prevMarkdown: string) => {
              onMarkdownValueChange && onMarkdownValueChange(markdown);
            }
          );
        bucketName &&
          ctx.update(uploadConfig.key, (prev: any) => ({
            ...prev,
            uploader,
          }));
        ctx.set(indentConfig, {
          type: 'space',
          size: 2,
        })
      })
      .config(nord)
      .use(listener)
      .use(commonmark)
      .use(history)
      .use(gfm)
      .use(indent)
      .use(upload);
  }, []);
```

**Comment by Saul-Mirone** [comment]
It should be `ctx.set(indentConfig.key, {...})`

**Comment by ningkehua** [comment]
> It should be `ctx.set(indentConfig.key, {...})`

Thanks a lot! It works for me. 
I previously referred to the document examples, and I think maybe the examples should be modified and corrected.

**Comment by daveteu** [comment]
Sorry for reviving this post, but it's related. I used `indentConfig.key` but it returned type error

<img width="1457" alt="image" src="https://github.com/Milkdown/milkdown/assets/18649392/559bd364-7c16-4367-b86e-428be78df9ee">
