### ISSUE TITLE
[Feature] Can Milkdown be wrapped as a Form Component

### ISSUE THREAD

**Issue by ningkehua** [Milkdown/milkdown#1048]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

I want to know if it's possible to wrap Milkdown as a Form Component.
But I can't find any docs about this.

### Solution

If possible, I can use it in a unified management form, such as Antd Form.

### Alternatives

No alternative solution.

**Comment by Saul-Mirone** [comment]
What do you mean by form component? Don't know much about antd. But you can set the input and get output of the editor so I guess it can be used in a form.
