### ISSUE TITLE
[Feature] Bind to YText instead of YDoc

### ISSUE THREAD

**Issue by nottherealsanta** [Milkdown/milkdown#1058]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

Currently the editor binds to YDoc, this makes it hard to have multiple editors. 

### Solution

An approach like that of y-monaco, which binds to YText would be great. 

### Alternatives

 Not sure

**Comment by Saul-Mirone** [comment]
I don't think bind to YDoc will stop you have multiple editors. And milkdown use prosemirror-yjs and I believe that's the best practice.
