### ISSUE TITLE
[Bug] When setting bold, italic, strikethrough multiple times, there is a problem

### ISSUE THREAD

**Issue by zhjin024399** [Milkdown/milkdown#1061]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.2.4

### Steps to reproduce

https://milkdown.dev/playground

When setting bold, italic, strikethrough multiple times
It works wrong 
like the line：
You **can ch*eck the output***\* markdow\*n text in **two columns editing**.

The same problem exists with native code.

### Expected behavior

Dont show \*

### Actual behavior

show some \* \~\~

### Runtime

Chrome, Safari, Firefox, Electron, Other (please specify in steps to reproduce)

### OS

Windows

### Build and bundle tools

Webpack, Create React App

**Comment by Saul-Mirone** [comment]
Please provide more detailed steps to reproduce.

**Comment by zhjin024399** [comment]
For example：
abcdefghijklmn

1. select ’abcdef‘ to set bold
2. select  'cdefgh' to set italic
3. select 'efghij' to set strikethrough 


> Please provide more detailed steps to reproduce.

**Comment by zhjin024399** [comment]
`ctx.update(inlineSyncConfig.key, (prevCfg) => {
              return {
                ...prevCfg,
                shouldSyncNode: () => false,
              };
            });`

When add this code, it's good

**Comment by Saul-Mirone** [comment]
Still cannot reproduce

https://github.com/Milkdown/milkdown/assets/10047788/1d877f04-3450-4095-8ec3-547d230ff2b7

I think maybe your question duplicated with https://github.com/Milkdown/milkdown/issues/956#issuecomment-1493657219
