### ISSUE TITLE
Color extension

### ISSUE THREAD

**Issue by nickbe** [Milkdown/milkdown#1069]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

Some other markdown editors have implemented several approaches to add color support. My own thoughts would be to have some simple hitherto unused tags which are not too intrusive when in plain text mode.

has anyone tried something like this for milkdown? 

### Solution

Maybe a new extension

### Alternatives

Make me shut up verbally because it's no good :grin

**Comment by Saul-Mirone** [comment]
I don't have plan to support it officially because it's a none standard markdown syntax. But I would love to see it as a community plugin.
