### ISSUE TITLE
Youtube or Vimeo iFrame integration

### ISSUE THREAD

**Issue by nickbe** [Milkdown/milkdown#1081]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

Has anyone thought about using youtube or similar to directly show videos inline? 
Is there a working solution for this?

### Solution

Just a link currently

### Alternatives

Show a real iFrame

**Comment by Saul-Mirone** [comment]
It's similar to https://milkdown.dev/docs/plugin/example-iframe-plugin. You can implement a plugin for this.
