### ISSUE TITLE
[Feature] `updateLinkCommand` should update the display text of the link

### ISSUE THREAD

**Issue by mggrand** [Milkdown/milkdown#1089]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

First, I really appreciate your work and milkdown is awesome! 🚀

When using the `updateLinkCommand` we can pass a payload in form of
```
{
 href: "www.somelink.com",
 title: "Somelink"
}
```
my understanding of this was, if i update the title the text which is shown in milkdown will change to this text. Instead, only the `title` attribute of the `<a>` tag is updated.

### Solution

Update the text which is shown in milkdown with the title from the payload.

### Alternatives

Add a `text` attribute to the payload interface which will update the text.

**Comment by Saul-Mirone** [comment]
Markdown:
```markdown
[link](/uri "title")
```

Rendered:
[link](/uri "title")

---

`link` is text, `/uri` is href, `title` is title

https://spec.commonmark.org/0.18/#links

**Comment by mggrand** [comment]
@Saul-Mirone 
I was not clear enough about my request. I am aware about the feature you mentioned when writing a link directly in the editor. But if you have a button let's call it "Edit link" where you open some modal to edit the link then you call the `updateLinkCommand` on the editor from [here](https://github.com/Milkdown/milkdown/blob/4bfdc92eeed0d0387d02e9845ddce41ab5045e58/packages/preset-commonmark/src/mark/link.ts#L77C14-L77C32). But this command only accepts `title` and `href`. It would be nice if this command also could update the `link`

**Comment by mggrand** [comment]
@Saul-Mirone
Am I using this functionality the wrong way?

**Comment by Saul-Mirone** [comment]
In fact in the architecture of ProseMirror. A link is just a `Mark`, which means it only holds the attributes without the content. So you're looking for a way to modify the content, you should use something like https://prosemirror.net/docs/ref/#state.Transaction.insertText
