### ISSUE TITLE
[Feature] Can we separate TaskList schema from task-list-item MilkdownPlugin

### ISSUE THREAD

**Issue by sytolk** [Milkdown/milkdown#1091]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

https://github.com/Milkdown/milkdown/blob/aabeffa126720405be492c51e51f8458d06abea2/packages/preset-gfm/src/node/task-list-item.ts#L12

Now we cannot add new command like InsertTaskList - the reason is that taskList schema is in task-list-item Plugin only.

To add taskList checkbox I have try to insert node from listItemSchema but without success:
```javascript
import {listItemSchema} from "@milkdown/preset-commonmark";

export const insertTaskListCommand = $command(
    'InsertTaskList',
    ctx => () => (state, dispatch) => {
      if (!dispatch) return true;

      const { tr, selection } = state;

      const node = listItemSchema.type(ctx).create()
      if (!node)
        return true

      dispatch(tr.replaceSelectionWith(node).scrollIntoView())
      return true;
    }
);
```

### Solution

extract from task-list-item in new file TaskListSchema.ts that can be usable for new commands.

### Alternatives

...

**Comment by sytolk** [comment]
https://github.com/orgs/Milkdown/discussions/1028

**Comment by Saul-Mirone** [comment]
The task list item is just the same as list item with the `checked` attribute. You can add commands for list item and check if it holds the `checked` attribute. The reason why I combine them is that if you separate them, they'll need the same keymap and they'll conflict in some cases.

**Comment by sytolk** [comment]
@Saul-Mirone how to add the command insertTaskList item? Chekbox

**Comment by Saul-Mirone** [comment]
1. About the command
```ts
export const insertTaskListCommand = $command(
  'InsertTaskList',
  (ctx) => () => (state, dispatch) => {
    if (!dispatch) return true;

    const { tr } = state;
    //const { from } = selection;

    const node = listItemSchema.type(ctx).create({ checked: false });
    //                                                                                    ^ change here
    if (!node) return true;

    return true;
  }
);
```

2. About the style
You need to implement a custom task list item since we're headless now. Like what I did in playground:https://github.com/Milkdown/website/blob/main/src/components/playground-editor/editor-component/ListItem.tsx
Another good news is that I'm working on a component library which contains one can work out of box.

**Comment by sytolk** [comment]
@Saul-Mirone it works I can create checkbox but I have error using create() 
![image](https://github.com/Milkdown/milkdown/assets/1415463/cfdac9e9-1f3d-4b12-a7e8-d36ad7a15826)

if I use createChecked
`const node = listItemSchema.type(ctx).createChecked({ checked: false });`
I have eror: `RangeError: Invalid content for node list_item: <>`
it appears that children of the listItem is missing

But it works with ` const node = listItemSchema.type(ctx).createAndFill({ checked: false });`
You can add in playground demo Toolbar new TaskList button. 
Thanks!

**Comment by sytolk** [comment]
@Saul-Mirone insertTaskListCommand works and create new checkbox but cursor and textSelection appears on the next line. How can I write text next to the checkbox created?
