### ISSUE TITLE
is Active 

### ISSUE THREAD

**Issue by pygc** [Milkdown/milkdown#1117]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

Can I use the "is active" functionality in the editor to check if the current editing content is active? Something like:  editor.isActive("strong").

### Solution

editor.isActive("strong").

### Alternatives

like tiptap：
editor.can().chain().focus().toggleBold().run()

**Comment by pygc** [comment]
ok!
        listener.updated((ctx) => {
          const state = ctx.get(editorStateCtx);
          const schema = ctx.get(schemaCtx);
          ctxStyle.isBold = hasMark(state, schema.marks.strong);
          ctxStyle.isItalic = hasMark(state, schema.marks.em);
          ctxStyle.isStrike = hasMark(state, schema.marks.strike_through);
        });

**Comment by pygc** [comment]
function hasMark(state, type) {
  if (!type) return false;
  const { from, $from, to, empty } = state.selection;
  if (empty) return !!type.isInSet(state.storedMarks || $from.marks());
  return state.doc.rangeHasMark(from, to, type);
};

**Comment by Saul-Mirone** [comment]
Seems you've already found the solution.

**Comment by pygc** [comment]
还有个问题，就是listener的updated不能监控到游标位置变化，或者按下的情况

**Comment by pygc** [comment]
我在做一个菜单，按钮需要标示bold等情况，做不出来

**Comment by pygc** [comment]
我修改了listener，解决问题了
