### ISSUE TITLE
Use bold in inline-code

### ISSUE THREAD

**Issue by SunnyCheung-cp** [Milkdown/milkdown#1126]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.30

### Steps to reproduce

Typing text:  `testing **bold** test` or `testing *italic* test`

https://github.com/Milkdown/milkdown/assets/105030733/7b38dabf-6487-488e-85aa-851ca5259f05

### Expected behavior

shows bold/italic in inline-code

### Actual behavior

Unable to show

### Runtime

Chrome

### Build and bundle tools

Webpack

**Comment by Saul-Mirone** [comment]
Show bold/italic in inline code is not the right behavior in markdown according to markdown spec. The only way is to wrap a inline code in bold/italic, like **`cold`** (\*\*\`cold`**).
