### ISSUE TITLE
link plugin

### ISSUE THREAD

**Issue by pygc** [Milkdown/milkdown#1127]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

为什么我的链接点击后也打不开，没有显示链接地址![image](https://github.com/Milkdown/milkdown/assets/4996887/7f96cc84-9c78-403f-8d19-c3d8c4b1d618)

希望像官网一样能打开链接：
![image](https://github.com/Milkdown/milkdown/assets/4996887/947c1606-73a2-4f4b-85e2-266e77705905)

### Solution

希望像官网一样能打开链接：
![image](https://github.com/Milkdown/milkdown/assets/4996887/947c1606-73a2-4f4b-85e2-266e77705905)

### Alternatives

无需

**Comment by SunnyCheung-cp** [comment]
@pygc  I think you need to add link widget component
You can view it [here](https://github.com/DareData/notion-style-editor), @zgrybus thanks to the production
![image](https://github.com/Milkdown/milkdown/assets/105030733/7db61400-fe5e-4e90-9c6d-68e8d15e654b)

**Comment by pygc** [comment]
@SunnyCheung-cp 看起来用了tooltip，我试着参考一下，谢谢

**Comment by pygc** [comment]
@SunnyCheung-cp Thank you, it work for me
