### ISSUE TITLE
bold display wrong

### ISSUE THREAD

**Issue by SunnyCheung-cp** [Milkdown/milkdown#1142]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.30

### Steps to reproduce

1. Input the hello, bold college 
2. Press the space, the input hello again, bold college 
3. Unbold the last hello

https://github.com/Milkdown/milkdown/assets/105030733/230901ef-281f-4c08-8fd1-f37bff8a988c

### Expected behavior

The first hello can be successfully bold

### Actual behavior

Display **hello**

### Runtime

Chrome

### OS

macOS

### Build and bundle tools

Create React App

**Comment by SunnyCheung-cp** [comment]
@Saul-Mirone  I think it's not just bold display wrong, it's all toggleMark
And we can't undo it to get it back to normal display, we'll fixing it?

https://github.com/Milkdown/milkdown/assets/105030733/90f64864-47e9-476f-b9c5-0f558bc3bddf

**Comment by Saul-Mirone** [comment]
This issue should be split into 2 different problems:

1. When user typing `*hello *hello`, **you will not get bold style** because that's how markdown spec defines the behavior.
   `*hello *hello` -> *hello *hello. It's same in github's editor.
2. Users cannot undo the behavior. That's a bug and I'll fix it.

**Comment by SunnyCheung-cp** [comment]
@Saul-Mirone  
`**bold ** bold` this is a wrong markdown format
As you can see from the video I shared, when I type `strong testing` and set it to bold, it is fine
But when I want to cancel `testing` blod, it appears in the wrong format, `**strong testing** -> **strong **testing`
That's not correct, right?   It should be `**strong** testing`

**Comment by Saul-Mirone** [comment]
Fixed by https://github.com/Milkdown/milkdown/pull/1171
