### ISSUE TITLE
[Bug] GapCursor plugin does not work with mouse clicks

### ISSUE THREAD

**Issue by dorkster100** [Milkdown/milkdown#1210]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.3.2

### Steps to reproduce

Gapcursor cannot be activated using mouse click.

1. Go to playground
2. Go to the section with the table
3. Click below the table between `<hr>` and table
4. Gap cursor html is not inserted 

If you click on last cell and hit arrow down, then it is properly inserted

### Expected behavior

By my understanding, mouse click should trigger insertion of the gap element

I am not 100% sure that this is expected behaviour, as my experience is little with prosemirror and milkdown. However the prosemirror-gapcursor package has handleClick event and the `valid` check fails. It is a bit hard for me to debug it further, as I currently am a bit struggling with understanding basic concepts like ContentMatch.

The *valid* fails first at *parent* being paragraph which *isTextBlock* and then at *parent.contentMatchAt($pos.index()).defaultType* beind hardbreak.

### Actual behavior

No gap element is inserted.

Also playground does not import gapcursor.css, so the gap is not visible, but maybe this is intentional.

### Runtime

Firefox

### OS

Linux

### Build and bundle tools

Vite

**Comment by Saul-Mirone** [comment]
It works now after some configuration. You can take a look at https://github.com/Milkdown/milkdown/blob/main/packages/crepe/src/feature/gap-cursor/index.ts for an example.
