### ISSUE TITLE
[Bug] blockView is not exported from @milkdown/plugin-block

### ISSUE THREAD

**Issue by athanclark** [Milkdown/milkdown#1224]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.3.3

### Link to runnable example

https://codesandbox.io/p/sandbox/confident-ritchie-d9lv98?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrgqtm0t00062869o1p8elza%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrgqtm0s00022869zokvcg6g%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrgqtm0s00032869tqcjeznk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrgqtm0t00052869k6ipeal1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrgqtm0s00022869zokvcg6g%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrgqtm0s00012869enx5bqfj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrgqvcre003l2869jjtl3kyt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A48%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A48%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrgqtm0s00022869zokvcg6g%2522%252C%2522activeTabId%2522%253A%2522clrgqvcre003l2869jjtl3kyt%2522%257D%252C%2522clrgqtm0t00052869k6ipeal1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrgqtm0s00042869ko3zmcxb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrgqtm0t00052869k6ipeal1%2522%252C%2522activeTabId%2522%253A%2522clrgqtm0s00042869ko3zmcxb%2522%257D%252C%2522clrgqtm0s00032869tqcjeznk%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrgqtm0s00032869tqcjeznk%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

Importing the `blockView` field from `@milkdown/plugin-block` is undefined, opposed to the [instructions](https://milkdown.dev/docs/api/plugin-block).

### Expected behavior

I would assume there to be some kind of object there. I grep'd the plugin source code and couldn't find anything for `blockView`.

### Actual behavior

Build fails.

### Runtime

Chrome, Firefox

### OS

Linux

### Build and bundle tools

Rollup, Vite

**Comment by Saul-Mirone** [comment]
The documentation is out dated. There's no `blockView` in block now. Checkout https://github.com/Milkdown/milkdown/blob/main/packages/crepe/src/feature/block-edit/handle/index.ts#L75
