### ISSUE TITLE
[Bug] hybrid mode not working although #819 is closed

### ISSUE THREAD

**Issue by kajogo777** [Milkdown/milkdown#1250]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.3.5

### Steps to reproduce

Point the cursor on a markdown line

### Expected behavior

Line to turn to text showing symbols like `#`

### Actual behavior

Nothing changes and styling stays the same

### Runtime

Chrome

### OS

Linux

### Build and bundle tools

Vite

**Comment by Saul-Mirone** [comment]
Hybrid mode is more a ux pattern than a feature. It can be defined in many different ways by different users. I closed it because it's out of scope.
