### ISSUE TITLE
[Bug]Selecting the editor causes the iframe to disappear

### ISSUE THREAD

**Issue by YueXingyu5482** [Milkdown/milkdown#1254]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

    "@milkdown/core": "^7.3.5",     "@milkdown/preset-commonmark": "^7.3.5",     "@milkdown/preset-gfm": "^7.3.5",     "@milkdown/theme-nord": "^7.3.5",     "@milkdown/utils": "^7.3.5",     "@milkdown/vue": "^7.3.5",     "remark-directive": "^3.0.0",     "vue": "^3.4.15"

### Steps to reproduce

If the default value in the editor is only iframe, the iframe disappears when the editor is selected
`import { InputRule } from '@milkdown/prose/inputrules'
import { $node, $inputRule, $remark } from "@milkdown/utils"
import directive from 'remark-directive';

const remarkPluginId = "iframe"
const remarkDirective = $remark(remarkPluginId, () => directive)
const iframeNode = $node('iframe', () => ({
    group: 'block',
    atom: true,
    isolating: true,
    marks: '',
    selectable: true,
    draggable: true,
    defining: true,
    attrs: {
        src: { default: null },
    },
    parseDOM: [{
        tag: 'iframe',
        getAttrs: (dom) => ({
            src: dom.getAttribute('src'),
        }),
    }],
    toDOM: (node) => [
        'iframe',
        { ...node.attrs, 'contenteditable': false },
        0,
    ],
    parseMarkdown: {
        match: (node) => {
            return node.type === 'leafDirective' && node.name === 'iframe'
        },
        runner: (state, node, type) => {
            state.addNode(type, { src: node.attributes.src });
        },
    },
    toMarkdown: {
        match: (node) => node.type.name === 'iframe',
        runner: (state, node) => {
            state.addNode('leafDirective', undefined, undefined, {
                name: 'iframe',
                attributes: { src: node.attrs.src },
            });
        },
    }
}))
const iframeInputRule = $inputRule((ctx) => new InputRule(/::iframe\{src="(?<src>[^"]+)?"?\}/, (state, match, start, end) => {
    const [okay, src = ''] = match;
    const { tr } = state;

    if (okay) {
        tr.replaceWith(start - 1, end, iframeNode.type(ctx).create({ src }));
    }

    return tr;
}))
export default [iframeInputRule, iframeNode, remarkDirective]`

### Expected behavior

The editor is selected, and the contents of the editor are not affected

### Actual behavior

The editor is selected, but the iframe is deleted

### Runtime

Chrome

### OS

macOS

### Build and bundle tools

Vite

**Comment by Saul-Mirone** [comment]
Should be fixed.
