### ISSUE TITLE
[Bug]  @milkdown/components/link-tooltip  live edit links have no effect

### ISSUE THREAD

**Issue by qiuweikangdev** [Milkdown/milkdown#1257]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.3.5

### Steps to reproduce

https://stackblitz.com/github/Milkdown/examples/tree/main/component-link-tooltip

### Expected behavior

![image](https://github.com/Milkdown/milkdown/assets/44153172/0c66cb80-20af-4f00-a031-9930e10d1c6b)

### Actual behavior

would like to show the link effect when the full link is entered in real time
Also how to customize link-tooltip based on @milkdown/components/link-tooltip, can you give a more complete example?

### Runtime

Chrome

### OS

Windows

### Build and bundle tools

Vite

**Comment by Saul-Mirone** [comment]
The example has been updated.

**Comment by knownasilya** [comment]
@Saul-Mirone is there an example where you customize what is inside the tooltip?
