### ISSUE TITLE
[Bug] Examples: Vue Block v7.3.5 has a problem where the block hides when the width of the editor changes

### ISSUE THREAD

**Issue by qiuweikangdev** [Milkdown/milkdown#1260]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.3.5

### Link to runnable example

https://stackblitz.com/edit/github-ybtsh2?file=package.json

### Steps to reproduce

When the width of the editor is stretched, the custom block cursor-grab is hidden and not shown.
The tooltipBlock is not showing up
![image](https://github.com/Milkdown/milkdown/assets/44153172/90620ec2-027c-4ee2-b632-7d089c7885eb)

### Expected behavior

Changes to the editor width also require the display of the block cursor grab

### Actual behavior

For now, the block is hidden.

**Comment by jbmaisner** [comment]
same behavior here... seems it works only on specific window width range (see screen recording)

https://share.cleanshot.com/8Dshw4W5
