### ISSUE TITLE
XSS in latest version(v7.3.5) when rendering classDiagram[Bug]

### ISSUE THREAD

**Issue by sunriseXu** [Milkdown/milkdown#1267]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

v7.3.5

### Link to runnable example

https://milkdown.dev/playground?text=AYi2FMCdQQwSwCYCgDGAbGBnTAROMBzSGUJAYQ2wAYBGAAgB4AfAWhbuAEEA3KATwAyAewB2BClkwM4oAnUyQUAXgDkADxV1RUSEMhKYaKABcAFAiEoArhBHGAdCiFCA1nHABKAHzBylTFQAzHQAVGx0EtQALH6SVACsWuGRAQBssdQA7HT29hH%2BVAAcGQH0AFzycABe4KYeJbR0FXB2dCgAFjIADg3ldC3GdAR6cGgYSCC%2BSEA%3D

### Steps to reproduce

1. Open [https://milkdown.dev/playground](https://milkdown.dev/playground)
2. In playground, just enter ````mermaid`, in text section, input following payload
```
classDiagram
Class01 <|-- `AveryLongClass<img src='x' onerror=alert(document.domain)>`
Class03 *-- Class04
Class05 o-- Class06
Class07 .. Class08
Class01 : size()
Class01 : int chimp
Class01 : int gorilla
```
3. click ok, the alert should be fired
![milkdown-xss](https://github.com/Milkdown/milkdown/assets/33363160/a21cd9e3-b9bb-425b-be29-1f2f757132e9)

### Expected behavior

node names in classDiagram should be rendered sanitized, any event listener should be safely filted.

### Actual behavior

node name in classDiagram can be injected with xss payload

### Runtime

Chrome

### OS

Windows

### Build and bundle tools

Webpack

**Comment by quank123wip** [comment]
Seems working fine in official mermaid editor, maybe associated with the version milkdown uses?

**Comment by sunriseXu** [comment]
Yes, I just tested the mermaid editor with [official repo](https://github.com/mermaid-js/mermaid-live-editor). The latest milkdown used mermaid v10.0.0 which is vulnerable for rendering classDiagram, the latest mermaid version 10.9.0 have fixed the problem, just updating mermaid to latest one could fix the problem.

**Comment by quank123wip** [comment]
> Yes, I just tested the mermaid editor with [official repo](https://github.com/mermaid-js/mermaid-live-editor). The latest milkdown used mermaid v10.0.0 which is vulnerable for rendering classDiagram, the latest mermaid version 10.9.0 have fixed the problem, just updating mermaid to latest one could fix the problem.

need further testing, have drafted a pull request for this.

**Comment by sunriseXu** [comment]
I have reproduced the bug in mermaid editor repo, following these steps in case you want to reproduce the bug:
1. git clone https://github.com/mermaid-js/mermaid-live-editor.git
2. edit the package.json, change mermaid version to v10.0.0
3. yarn install && yarn dev -- --open
4. using the payload I have provided in local editor, eg: http://localhost:3000/, the xss payload should be triggered
