### ISSUE TITLE
[Bug] preset-gfm checkboxes not working correctly

### ISSUE THREAD

**Issue by boguz** [Milkdown/milkdown#1269]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.3.5

### Steps to reproduce

- Install dependencies
    - "@milkdown/core": "^7.3.5",
    - "@milkdown/plugin-listener": "^7.3.5",
    - "@milkdown/preset-commonmark": "^7.3.5",
    - "@milkdown/preset-gfm": "^7.3.5",
    - "@milkdown/theme-nord": "^7.3.5",
- initialize the editor:
```js
this.markdownEditor = await Editor
    .make()
    .config((ctx) => {
        ctx.set(rootCtx, this.taskDescriptionRef.value)
        ctx.set(defaultValueCtx, placeholderText)
    })
    .config(nord)
    .use(commonmark)
    .use(gfm)
    .create();
```
- try creating a checkbox list in the editor

### Expected behavior

I expected to get a checkbox when i add either `[ ] test one` or `* [ ] test one` in the editor.

This is not my example, and here they use v7.1 instead of 7.3.5, but you can also see the same problem here:
https://codesandbox.io/p/devbox/milkdown-editor-example-cxxuw6?file=%2Fpackage.json

### Actual behavior

Instead i get:
- `[ ] test` when i add `[ ] test`
- `* test` when i add `* [ ] test`
<img width="113" alt="image" src="https://github.com/Milkdown/milkdown/assets/15846102/c82475eb-0887-4c30-b0fe-ee7c377b8bbc">

This is the markup i see in the inspector:
<img width="477" alt="image" src="https://github.com/Milkdown/milkdown/assets/15846102/19ed5ec9-1542-4c5e-a69e-619855dfa1a5">

### Runtime

Chrome

### OS

macOS

### Build and bundle tools

Vite

**Comment by C-FWES** [comment]
Jumping in since I faced a similar issue a while ago - you most likely need to define a `ListItem` component similar to the [one found on the website repo](https://github.com/Milkdown/website/blob/main/src/components/playground-editor/editor-component/ListItem.tsx).

Then import both that component, and `listItemSchema` from the preset-commonmark library. Subsequently if you configure your editor with a list item schema definition like so, you should be able to use the gfm checkbox syntax without issue:

```
this.markdownEditor = await Editor
    .make()
    .config((ctx) => {
        ctx.set(rootCtx, this.taskDescriptionRef.value)
        ctx.set(defaultValueCtx, placeholderText)
    })
    .config(nord)
    .use(commonmark)
    .use(gfm)
    .use(
          $view(listItemSchema.node, () =>
            nodeViewFactory({ component: ListItem })
          )
      )
    .create();
```

**Comment by boguz** [comment]
Thank you @C-FWES . I have tried that, but i didn't get it to work. :/
Where should i import `$view` and the `nodeViewFactory` from (i am not using react)?

It would be nice if this would work, but i think it should also work without this extra `use(...)` configuration. On the docs i don't find anything about it...

**Comment by Saul-Mirone** [comment]
You can just install the `@milkdown/components` package and use it like what I did here:

https://github.com/Milkdown/milkdown/blob/main/e2e/src/list-item-block/main.ts#L44
