### ISSUE TITLE
[Feature] highlight.js plugin. Open to PR?

### ISSUE THREAD

**Issue by Banner-Keith** [Milkdown/milkdown#1286]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

I'm interested in using highlight.js instead of prism since it's already in our codebase.

### Solution

Would you be open to a PR with a new plugin for highlight.js?

### Alternatives

If this isn't supported I can publish my own package.

**Comment by Saul-Mirone** [comment]
Thanks for asking. Publish your own package please. I prefer more community plugins instead of official plugins.
