### ISSUE TITLE
[Feature] Code block supports displaying line numbers

### ISSUE THREAD

**Issue by Ligayu** [Milkdown/milkdown#1288]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

I want every line of the code block to be wrapped in a class.
like: 
![image](https://github.com/Milkdown/milkdown/assets/60767980/6cfa03b0-2249-4bcc-97f4-10d566c1c02a)
Then I can simply add css and display the line number.
like： 
    code {
        counter-reset: step;
        counter-increment: step 0;
      }
      
      code .line::before {
        content: counter(step);
        counter-increment: step;
        width: 1rem;
        margin-right: 1.5rem;
        display: inline-block;
        text-align: right;
        color: rgba(115,138,148,.4)
      }

### Solution

none

### Alternatives

none

**Comment by Saul-Mirone** [comment]
You can use [code-block-component](https://milkdown-storybook.vercel.app/?path=/story/components-code-block--javascript), which has the code mirror integration with a lot of features, including line numbers.
