### ISSUE TITLE
[Bug] Uptake @atomico/hooks@4.1.2 with licensing fix

### ISSUE THREAD

**Issue by mig8447** [Milkdown/milkdown#1294]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@milkdown/components

### Steps to reproduce

The @atomico/components package used by @milkdown/components is not licensed prior to 4.1.2

### Expected behavior

All 3rd and 4th party components should be licensed

### Actual behavior

No package under @atomico/hooks is properly licensed before version 4.1.2

### Runtime

Other (please specify in steps to reproduce)

### OS

Other (please specify in steps to reproduce)

### Build and bundle tools

Vite, Other (please specify in steps to reproduce)

**Comment by Saul-Mirone** [comment]
Closing in favor of https://github.com/Milkdown/milkdown/commit/e63bb20d8ad5d110ee4d1904447fed59dd163aee
