### ISSUE TITLE
[Bug]Math_block does not work

### ISSUE THREAD

**Issue by wuzesheng** [Milkdown/milkdown#1307]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.3.6

### Steps to reproduce

Hi there,
I configured math plugin in my Milkdown editor, but when I typed $$ in my editor, it just lost the focus, and I coundn't type the math content anymore.
Anyone can help on this, thanks!

### Expected behavior

Input the math content after I typed the $$ + enter

### Actual behavior

Lost the focus, and can't type the math content after I typed $$ + enter

### Runtime

Electron

### OS

macOS

### Build and bundle tools

Vite

**Comment by Saul-Mirone** [comment]
Technically it's not broken, for now you need to write a renderer to render the user interface like how I did it in https://github.com/Milkdown/website/blob/main/src/components/playground-editor/editor-component/MathBlock.tsx

I plan to build a plugin that can make it work out of box in `@milkdown/components` lib in the future. But the design is not ready yet.
