### ISSUE TITLE
[Feature] markdown link support target="_blank"

### ISSUE THREAD

**Issue by ningkehua** [Milkdown/milkdown#1314]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

I want my browser to open a new window when I click the link.
I can't find information to implement this.

The following code cannot be parsed by milkdown:
· `[example](http://yinping4256.github.io){:target="_blank"}`
· `<a href=" " target="_blank">https://bing.xinac.net</a >`

![image](https://github.com/Milkdown/milkdown/assets/58503079/909f5861-3869-496d-a7d8-d8abe7921ec4)

### Solution

I can set something to support the link to open a new window when I click it.

### Alternatives

none

**Comment by ningkehua** [comment]
We can custom link node or use [handleClickOn] to
rewrite the click handler.
(https://prosemirror.net/docs/ref/#view.EditorProps.handleClickOn)https://github.com/Milkdown/milkdown/issues/867

**Comment by irelib** [comment]
> We can custom link node or use [handleClickOn] to rewrite the click handler. ⬇️ https://prosemirror.net/docs/ref/#view.EditorProps.handleClickOn)https://github.com/Milkdown/milkdown/issues/867

Hello, could you send the relevant implementation code?
