### ISSUE TITLE
[Bug] Copy ordered list, paste will become unordered list.

### ISSUE THREAD

**Issue by KunerRick** [Milkdown/milkdown#1353]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@milkdown/*: ^7.3.5

### Steps to reproduce

1. copy the following ordered list
```markdown
1. 333
2. 2222
3. 444
```
2. go to [playground](https://milkdown.dev/playground)
3. paste 

### Expected behavior

The paste should look like this
![image](https://github.com/Milkdown/milkdown/assets/23055512/72e431a5-63bb-4751-b65b-83c18e0043e5)

### Actual behavior

Display as an unordered list

![image](https://github.com/Milkdown/milkdown/assets/23055512/92c20b74-0b9b-4b0f-8b1a-ec75b4e074f5)

### Runtime

Chrome

### OS

Windows

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by benatkin** [comment]
I reproduced this and discovered #1362 in the process! Good catch.
