### ISSUE TITLE
[Bug] Links on React version don't allow you to click

### ISSUE THREAD

**Issue by alexjackhughes** [Milkdown/milkdown#1363]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.3.3

### Steps to reproduce

1. [Go here](https://stackblitz.com/github/Milkdown/examples/tree/main/react-commonmark?file=components%2FEditor.tsx)
2. Add a link to the markdown
3. Try to click the link (you can click through if you right-click) 

### Expected behavior

I'd expect to be able to click the link and for it to open either in that tab or a new tab

### Actual behavior

You click the link and nothing happens.

---

Apologies if this isn't an issue, and I'm missing some plugin; I did check and I couldn't find anything. Also, I'd be happy to help fix this issue if this isn't expected behaviour if you can just point me in the right direction of what's going on.

### Runtime

Chrome

### OS

macOS

### Build and bundle tools

Vite

**Comment by Saul-Mirone** [comment]
I think prosemirror disabled the click and open link feature. Please refer to [https://discuss.prosemirror.net/t/clickable-links/3628](https://discuss.prosemirror.net/t/clickable-links/3628)
