### ISSUE TITLE
[Bug] How do you add a toolbar?

### ISSUE THREAD

**Issue by shadow7412** [Milkdown/milkdown#1401]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.4.0

### Link to runnable example

N/A

### Steps to reproduce

On https://milkdown.dev/playground, the example is shown with a working toolbar. However I'm unable to find any documentation on how to actually enable it.

I've managed to find stuff like https://www.npmjs.com/package/@milkdown/plugin-menu (which I found by finding the PR for this feature on github) which seemed like the answer I needed, but it's deprecated with no guidance in the message as to what it has been replaced by.

### Expected behavior

Source code for the way the preview is set up would be nice to have available.
A message should be added to deprecated packages, guiding them to the acceptable alternatives.

### Actual behavior

There do not seem to be any examples of how to enable this (presumably very commonly required) feature, despite it being teased in the playground.

### Runtime

Firefox

### OS

Windows, Linux

### Build and bundle tools

Vite

**Comment by Saul-Mirone** [comment]
https://github.com/Milkdown/website/blob/main/src/components/playground-editor/index.tsx#L91C1-L117C13

**Comment by falk-stefan** [comment]
@Saul-Mirone the link is dead unfortunately. Do you have an example on how we can add a simple menu/toolbar like:

![Image](https://github.com/user-attachments/assets/45de4e3b-58df-4dbf-b122-8da3aad6f8da)
