### ISSUE TITLE
[Bug]After updating the plugin-tooltip to version 7.4.0, it is no longer functioning properly.Has there been any API change in this version?

### ISSUE THREAD

**Issue by skylkw** [Milkdown/milkdown#1409]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@milkdown/plugin-tooltip": "^7.4.0"

### Steps to reproduce

Update milkdown/plugin-tooltip to the latest version.The react-tooltip in the examples is not working properly, as the tooltip remains visible constantly.

### Expected behavior

![Uploading Snipaste_2024-07-09_13-55-02.png…]()

### Actual behavior

![Uploading Snipaste_2024-07-09_13-55-02.png…]()

### Runtime

Chrome

### OS

Windows

### Build and bundle tools

Vite

**Comment by skylkw** [comment]
<img width="1041" alt="Snipaste_2024-07-09_13-55-02" src="https://github.com/Milkdown/milkdown/assets/173221364/4a2b0d59-cbbf-4567-a55c-b06efab0b846">

**Comment by skylkw** [comment]
<img width="1069" alt="Snipaste_2024-07-09_13-53-23" src="https://github.com/Milkdown/milkdown/assets/173221364/dc7b8e5d-571e-47c0-b529-a7cd7c4b6fd9">

**Comment by Saul-Mirone** [comment]
The tooltip plugin has migrated from tippy to floating-ui because tippy has been deprecated. There're not many changes about API. You just need to add `absolute data-[show=false]:hidden` to your tooltip container. Please check the updated example here: https://github.com/Milkdown/examples/commit/41cfac0540ac07dd5f1d3d7da846bb4dd7b9b123
