### ISSUE TITLE
Support webpack4

### ISSUE THREAD

**Issue by Zackin-He** [Milkdown/milkdown#1433]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.4.0

### Steps to reproduce

My project uses nuxt2 and webpack4 behind it. When I run the project, I will report errors like @milkdown/prose/commands and other dependencies cannot be found. My preliminary judgment is as follows:
The package.json of @milkdown/prose package uses exports, imports and other new features only supported by webpack5, so webpack4 cannot find modules during compilation and construction. How should I solve this problem

### Expected behavior

Normal operation以上翻译结果来自有道神经网络翻译（YNMT）· 通用场景

### Actual behavior

These dependencies were not found:                                                                                                                                         friendly-errors 2:11:36 PM
                                                                                                                                                                           friendly-errors 2:11:36 PM
* #minpath in ./node_modules/@milkdown/core/node_modules/vfile/lib/index.js                                                                                                friendly-errors 2:11:36 PM
* #minproc in ./node_modules/@milkdown/core/node_modules/vfile/lib/index.js                                                                                                friendly-errors 2:11:36 PM
* #minurl in ./node_modules/@milkdown/core/node_modules/vfile/lib/index.js                                                                                                 friendly-errors 2:11:36 PM
* @milkdown/prose/commands in ./node_modules/@milkdown/core/lib/index.es.js                                                                                                friendly-errors 2:11:36 PM
* @milkdown/prose/inputrules in ./node_modules/@milkdown/core/lib/index.es.js                                                                                              friendly-errors 2:11:36 PM
* @milkdown/prose/keymap in ./node_modules/@milkdown/core/lib/index.es.js                                                                                                  friendly-errors 2:11:36 PM
* @milkdown/prose/model in ./node_modules/@milkdown/core/lib/index.es.js                                                                                                   friendly-errors 2:11:36 PM
* @milkdown/prose/state in ./node_modules/@milkdown/core/lib/index.es.js                                                                                                   friendly-errors 2:11:36 PM
* @milkdown/prose/view in ./node_modules/@milkdown/core/lib/index.es.js                                                                                                    friendly-errors 2:11:36 PM
* devlop in ./node_modules/@milkdown/core/node_modules/unified/lib/index.js                                                                                                friendly-errors 2:11:36 PM
* unist-util-visit-parents/do-not-use-color in ./node_modules/unist-util-visit-parents/lib/index.js                                                                        

### Runtime

Chrome

### OS

macOS

### Build and bundle tools

Webpack

**Comment by quank123wip** [comment]
Please reproduce your problem to help yourself and us to find potential solutions. You can give us an example project or create an example in stackblitz or codesandbox. I don't sure if there is a solution because nuxt2 and webpack4 are pretty old frameworks and become or has become EOL.I suggest you search the web for those standard problems at this time. Thanks for your participation.

**Comment by Zackin-He** [comment]
Why not provide dist directly in the npm package, so that don't depend on the version of the bundle tool?
