### ISSUE TITLE
[Feature] Allow passing options to floating ui in plugin-tooltip

### ISSUE THREAD

**Issue by edtownend** [Milkdown/milkdown#1436]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

Since moving from tippy to floating ui the only option that can be passed to floading ui is the offset parameter. For my specific use case I'd like to provide a custom value to placement (which is now hardcoded to 'top') but I could imagine other users might have other options. Thanks for considering this!

### Solution

Extend TooltipProviderOptions with a floatingUIOptions parameter similar to the tippyOptions parameter that came before

### Alternatives

Also select options such as placement could be added direct to TooltipProviderOptions

**Comment by Saul-Mirone** [comment]
Good point

**Comment by 3CordGuy** [comment]
This was a big oversight. I'm really surprised there would be this hard switch to a different dependency without exposing more config. It renders the tooltip very un-customizable in it's current form.

However I was able to get around it for now by building out a copy of the internal version of the `TooltipProvider` and just referencing that when constructing it with `new TooltipProvider()`.
