### ISSUE TITLE
[Feature] Bidirectional text support

### ISSUE THREAD

**Issue by avidseeker** [Milkdown/milkdown#1438]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

HTML text fields have `dir` attribute for specifying the direction of the text RTL or LTR (see also: [RTL-styling](https://rtlstyling.com/posts/rtl-styling)).

### Solution

It would be great if there is a shortcut/option/button to toggle text direction. This makes it easier to edit Bidi-mixed texts (e.g: Arabic and Latin).

### Alternatives

No.

**Comment by Saul-Mirone** [comment]
https://discuss.prosemirror.net/t/does-prosemirror-support-rtl-languages-editing/1318/2
