### ISSUE TITLE
[Bug]Project installation dependency running exception

### ISSUE THREAD

**Issue by Ajianxian** [Milkdown/milkdown#1445]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

the latest version in main branch

### Steps to reproduce

1. `git clone https://github.com/Milkdown/milkdown.git`
2. Enter the project directory and use pnpm to install dependencies.
3. Use `pnpm run start` to running the project, Error occurred
4. use `cnpm install -D tailwind-nord` to install dependencies, and rerun the project，Error occurred
5. Install ‘tailwind-nord’ dependencies, and rerun the project
6. Go to http://localhost:6006/, It was found that the website was abnormal and the page reported an error.

### Expected behavior

The website is running normally after starting the project locally

### Actual behavior

![2024-07-30_15445401](https://github.com/user-attachments/assets/ec583e7c-a588-49bc-9a56-dc26cc536a0f)

### Runtime

Chrome

### OS

Windows

**Comment by Ajianxian** [comment]
Step 6: Visit the website to display an exception and report an error.

![image](https://github.com/user-attachments/assets/86c06213-224d-48cb-adff-41b847c272fc)

**Comment by Saul-Mirone** [comment]
Please use `pnpm` and `corepack`.
