### ISSUE TITLE
[Bug] Paste markdown syntax text, no WYSIWYG

### ISSUE THREAD

**Issue by tcper** [Milkdown/milkdown#1496]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

all

### Steps to reproduce

Paste some markdown text, it is not showing WYSIWYG

https://github.com/user-attachments/assets/830fec61-64da-4df9-88ff-03319a3bb6a2

### Expected behavior

** text ** shows text bold

### Actual behavior

** text ** shows original text

### Runtime

Chrome

### OS

macOS

**Comment by Saul-Mirone** [comment]
** text ** is not bold in markdown. Paste it in github comment box and see the preview.
