### ISSUE TITLE
[Feature] add navigator to redirect heading like typora

### ISSUE THREAD

**Issue by lqh1008** [Milkdown/milkdown#1503]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

support redirect function

### Solution

support redirect function

### Alternatives

support redirect function

**Comment by Saul-Mirone** [comment]
Headings have uniq ids and can be redirected by #id
