### ISSUE TITLE
[Bug] Crepe toolbar buttons type are submit as the default html spec

### ISSUE THREAD

**Issue by ljcastroLemons** [Milkdown/milkdown#1521]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

 @milkdown/crepe": "^7.5.7"

### Steps to reproduce

iam working in a project that use strapi and iam replacing the WYSIWYG Editor following this link [strapi/wysiwyg]( https://strapi.io/blog/how-to-replace-strapi-s-default-wysiwyg-editor-with-tiny-mce-editor). We choose milkdown/crepe editor for this work and the main issue is that when we click into the toolbar bold button or the other ones the form is saved automatically.

### Expected behavior

Buttons in the toolbar or any others button should be type="button"

### Actual behavior

Buttons in the toolbar don specify type

### Runtime

Brave, Other (please specify in steps to reproduce)

### OS

Linux

### Build and bundle tools

Vite

**Comment by sindras** [comment]
Does this fixed your issue? #1530

**Comment by ljcastroLemons** [comment]
> Does this fixed your issue? #1530

yes thanks for the quick answer
