### ISSUE TITLE
[Question] Noobie question -Simple "js" file

### ISSUE THREAD

**Issue by ChriD** [Milkdown/milkdown#1527]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

**Sorry**, i am a noob in compiling / packing typescript.
I would like to use the editor in a simple website. Is there a prebuilt version or how can i create a simple js file from the typsecript files. I have tried using "tsc" to build the repo but that only throws a lot of errors. Can someone please give me a hint?

### Solution

I want to have a simple js file

### Alternatives

I dont know

**Comment by Saul-Mirone** [comment]
You need at least npm and run `npm install @milkdown/crepe`.
