### ISSUE TITLE
[Bug] when use Chinese Input method, after input, cursor auto move to head 

### ISSUE THREAD

**Issue by ryzencool** [Milkdown/milkdown#1528]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

open official website, in playground, input some chinese using chinese input method

![output](https://github.com/user-attachments/assets/09dfa098-95b5-44a9-9ef8-73cbf9c56abe)

### Expected behavior

after input,  the cursor is at the end of the line

### Actual behavior

cursor is at the head of the line

### Runtime

Chrome

### OS

Windows, Linux, macOS

### Build and bundle tools

Vite

**Comment by ryzencool** [comment]
It seems that only when use in react, this bug can be triggered

**Comment by tingjiangcao** [comment]
官网demo就有这个问题。

**Comment by xiayb** [comment]
We also encountered the same problem

**Comment by Saul-Mirone** [comment]
Fixed by https://github.com/Milkdown/milkdown/pull/1568
