### ISSUE TITLE
[Bug] (crepe)  Button type in table are not "type=button" 

### ISSUE THREAD

**Issue by ljcastroLemons** [Milkdown/milkdown#1531]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

 @milkdown/crepe": "^7.5.7"

### Steps to reproduce

Is the same issue solved here (https://github.com/Milkdown/milkdown/pull/1530) but for the table component in crepe editor

### Expected behavior

type button should be "type=button"

### Actual behavior

type button has the default value submit

### Runtime

Chrome

### OS

Linux

### Build and bundle tools

Vite

**Comment by TorstenDittmann** [comment]
@Saul-Mirone I can issue a PR here too if you want 👍🏻
