### ISSUE TITLE
[Bug] Chinese input, wrong cursor position.

### ISSUE THREAD

**Issue by tingjiangcao** [Milkdown/milkdown#1542]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

official website

### Steps to reproduce

Under ordered list and unordered list, input Chinese, the cursor position is wrong.
Correct: appears at the end.
Current: appears in the header.

中文输入列表项，光标位置错误。（来自官网的测试）

### Expected behavior

Current: appears in the header.

### Actual behavior

Current: appears in the header.

### Runtime

Chrome

### OS

Windows

### Build and bundle tools

Webpack

**Comment by yuri2peter** [comment]
The bug is still there.
