### ISSUE TITLE
[Bug] Explicit language list for @milkdown/kit/component/code-block isn't used with Crepe

### ISSUE THREAD

**Issue by seangwright** [Milkdown/milkdown#1547]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@milkdown/crepe@7.5.7

### Link to runnable example

https://stackblitz.com/edit/github-nfgjxq?file=src%2Fmain.ts

### Steps to reproduce

- Use Crepe
- Specify an explicit list of `languages` for the `@milkdown/kit/component/code-block` component

### Expected behavior

Only the languages that are specified for the `CodeBlockConfig` are loaded into the language selector dropdown

### Actual behavior

All languages included in `import { languages } from '@codemirror/language-data';` are loaded into the dropdown

### Runtime

Chrome

### OS

Windows, macOS

### Build and bundle tools

Vite

**Comment by seangwright** [comment]
I just realized that the customization approach with Crepe is different:

**Crepe**
```js
const crepe = new Crepe({
    root: editorEl,
    featureConfigs: {
      "code-mirror": {
        languages: myLanguages,
      },
    },
  });
```

**Manual**
```js
editor
  .config((ctx) => {
    ctx.update(codeBlockConfig.key, (defaultConfig) => ({
      ...defaultConfig,
      languages: myLanguages,
    }));
```

It seems when using Crepe I can add new plugins/components with the **Manual** approach, but I can't customize ones already loaded

```js
const crepe = new Crepe({
  root: editorEl,
  featureConfigs: {
    "code-mirror": {
      languages: myLanguages,
    },
  },
});

crepe.editor
  .config((ctx) => {
    const listener = ctx.get(listenerCtx);

    const updateField = debounce((ctx, markdown, prevMarkdown) => {
      if (markdown !== prevMarkdown) {
        console.log("markdown updated");
        textareaEl.value = c.getMarkdown().trim();
      }
    }, 250);

    listener.markdownUpdated(updateField);
  })
  .use(listener);
```

**Comment by Saul-Mirone** [comment]
The solution you've found is correct, in crepe you can use `featureConfigs` to define your own language list and the editor will only load the list you define.

**Comment by Saul-Mirone** [comment]
Now it's possible to not bundle all the languages by https://github.com/Milkdown/milkdown/pull/1928.
