### ISSUE TITLE
[Bug] Pressing backspace while using heading level 2+ cause unexpected behavior

### ISSUE THREAD

**Issue by sindras** [Milkdown/milkdown#1553]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

Crepe

### Steps to reproduce

Using the playground https://milkdown.dev/playground :

1. Try using a heading level 3 by typing `###`,
2. After that, delete the heading

### Expected behavior

Expected behavior is, once the heading is deleted, pressing backspace should bring me to the previous line.

### Actual behavior

But the actual behavior, is pressing backspace will change the heading level 3 to level 2. Pressing backspace one more time will change it to heading level 1. And finally pressing backspace again bringing the cursor back to the previous line.

This cause inconvenience for users.

**Comment by bayoudh-socrate** [comment]
The downgrade behavior can be handled with a custom command that converts a heading to a paragraph directly, rather than changing the heading level progressively.

Here's the code snippet:


```
export const downgradeHeadingCommand = $command("DowngradeHeading", (ctx) => () => (state, dispatch, view) => {
    const { $from } = state.selection;
    const node = $from.node();
    if (node.type !== headingSchema.type(ctx) || !state.selection.empty || $from.parentOffset !== 0) return false;

    return setBlockType(paragraphSchema.type(ctx))(state, dispatch, view);
});

withMeta(downgradeHeadingCommand, {
    displayName: "Command<downgradeHeadingCommand>",
    group: "Heading",
});

```

**Comment by sindras** [comment]
Thank you for the code snippet! This is very helpful 💯
