### ISSUE TITLE
[Bug] Conflict Between Link and Strong Marks in Milkdown

### ISSUE THREAD

**Issue by bayoudh-socrate** [Milkdown/milkdown#1555]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.5.0

### Steps to reproduce

When using both the link and strong marks together, I encountered an issue where the markdown syntax for bold (**) remains visible in the editor. 

This issue specifically occurs when I try to apply the link and bold formatting to only part of a string
However, if I apply both marks to the entire string, everything works correctly, and no markdown syntax is displayed.

----------------------------

<img width="1492" alt="Screenshot 2024-09-19 at 6 27 30 PM" src="https://github.com/user-attachments/assets/695efc7c-f4f8-4bda-8375-bff6dad4b15e">

----------------------------

**Same problem:**

<img width="1493" alt="Screenshot 2024-09-19 at 7 15 01 PM" src="https://github.com/user-attachments/assets/70dfa353-9377-49d3-82b5-8436cf1b23f3">

----------------------------

<img width="693" alt="Screenshot 2024-09-19 at 7 23 54 PM" src="https://github.com/user-attachments/assets/0d10fae2-00ff-4de2-82a6-98273328018f">

----------------------------

**Steps to Reproduce:**

1. Create a string, for example, "milkdown."
2. Apply link and strong formatting to a portion of the word, such as "dow."
3. Notice that the ** markdown syntax is still displayed between the text.
4. Now, apply both link and strong marks to the entire word "milkdown."
5. Observe that the formatting works correctly, and no markdown syntax is shown.

### Expected behavior

The ** syntax should not be displayed when applying both link and strong marks to part of a string, and the bold formatting should render without showing the raw markdown.

### Actual behavior

When applying both link and strong marks to part of a string, the ** markdown syntax for strong remains visible. This does not occur when the entire string is formatted with both marks.

**Video demonstration:** @Saul-Mirone this is a video example :  https://github.com/user-attachments/assets/ad354214-a975-4ed8-b478-2506e918903c

### Runtime

Chrome

### OS

macOS

### Build and bundle tools

Next.js

**Comment by Saul-Mirone** [comment]
That's how markdown specification defines the

See same behavior in github:

> code: `123**[Milkdown](https://milkdown.dev)**123`
> 
> render: 123**[Milkdown](https://milkdown.dev)**123

> code: `123 **[Milkdown](https://milkdown.dev)** 123`
> 
> render: 123 **[Milkdown](https://milkdown.dev)** 123

You can see more details in the original spec: https://spec.commonmark.org/0.31.2/#emphasis-and-strong-emphasis
