### ISSUE TITLE
[Bug] Buggy selection when using VanillaJs

### ISSUE THREAD

**Issue by eliakocher** [Milkdown/milkdown#1556]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.5.5

### Link to runnable example

https://stackblitz.com/edit/vitejs-vite-di4hzj

### Steps to reproduce

You need a VanillaJS or typescript project, DO NOT use a Framework like React or view.
You need a button to toggle the **strong** command

Select some text and click a button to make the selection **strong**
click the button again.
Try so select a single word or span the selection on multiple lines.

or use the code example:
```html
 <button id="clickMeButton">Click me</button>
 <div id="app"></div>
```
```typescript
import { defaultValueCtx, Editor, rootCtx } from '@milkdown/kit/core';
import { commonmark, toggleStrongCommand, } from '@milkdown/kit/preset/commonmark';
import { callCommand } from '@milkdown/kit/utils';


const markdown = `# Milkdown Vanilla Commonmark

> You're scared of a world where you're needed.

This is a demo for using Milkdown with **Vanilla Typescript**.`;

const editor = Editor.make()
  .config((ctx) => {
    ctx.set(rootCtx, '#app');
    ctx.set(defaultValueCtx, markdown);
  })
  .use(commonmark);

editor.create();

document.getElementById('clickMeButton')!.onclick = (e) => {
  editor.action(callCommand(toggleStrongCommand.key));
};
```

### Expected behavior

The selected text becomes bold
The selection is preserved

### Actual behavior

The selected text becomes bold
The selection moves around, or the selection is lost, depending on how much text you select.

if you select a single word, the selection is lost
if the selection spans multiple lines, the selection moves

Please note,  this issue is not present when using frameworks like Vue or React., but only with VanillaJs

![Screenshot 2024-11-07 at 13 11 06](https://github.com/user-attachments/assets/2090b190-3779-4745-9a53-02c4e1e6130a)

### Runtime

Chrome

### OS

macOS

### Build and bundle tools

Vite

**Comment by eliakocher** [comment]
using `onmousedown` instead of `onclick` in combination with `e.preventDefault();` seems to fix the problem.
But it's more a workaround rather than a true solution

**Comment by Saul-Mirone** [comment]
You'll at least import css from `@milkdown/prose/view/style/prosemirror.css` because that's how prosemirror works https://prosemirror.net/docs/ref/#view

> Make sure you load style/prosemirror.css as a stylesheet when using this module.

**Comment by eliakocher** [comment]
hello @Saul-Mirone, thanks for you answer.
importing the `prosemirror.css` doesn't seem to make any difference to the selection behaviour. Same as applying the nord-theme.

Have you tried the stackblitz and seen the buggy selection behaviour?

**Comment by Saul-Mirone** [comment]
I see, using `onmousedown` instead of `onclick` in combination with `e.preventDefault()` is the right solution provided by prosemirror.

https://prosemirror.net/examples/menu/#:~:text=this.dom.addEventListener(%22mousedown%22%2C%20e%20%3D%3E%20%7B%0A%20%20%20%20%20%20e.preventDefault()%0A%20%20%20%20%20%20editorView.focus()%0A%20%20%20%20%20%20items.forEach((%7Bcommand%2C%20dom%7D)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20if%20(dom.contains(e.target))%0A%20%20%20%20%20%20%20%20%20%20command(editorView.state%2C%20editorView.dispatch%2C%20editorView)%0A%20%20%20%20%20%20%7D)%0A%20%20%20%20%7D)

**Comment by eliakocher** [comment]
thank you! I was very confused because it works with react and vue  but not with vanillaJs.
Then I will keep using `onmousedown` and `e.preventDefault()`
