### ISSUE TITLE
[Bug] Cannot input link

### ISSUE THREAD

**Issue by bsuooo** [Milkdown/milkdown#1562]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"@milkdown/vue": "^7.5.0"

### Steps to reproduce

When I input [link]() in the editor, it is not transformed into <a></a>. Instead, the output displays as \[link]\(). I am not sure if the issue is caused by the \. However, if I set ctx.set(defaultValueCtx, '[link]()') during initialization, it displays correctly as <a></a>.

I would like to know the correct way to input a link

### Expected behavior

![image](https://github.com/user-attachments/assets/32f81bca-025f-4cc2-b4f2-c040570c3b02)
![image](https://github.com/user-attachments/assets/d6341762-1166-4f99-bf8d-3d5e9c38bf56)

### Actual behavior

null

### Runtime

Chrome

### OS

macOS

**Comment by quank123wip** [comment]
This bug has existed since 7.4.0, I found the last working version is 7.3.0. Need more time to find out how to fix it.

**Comment by quank123wip** [comment]
After a little digg'in, I think this may caused by extracting plugin-automd out of preset-commonmark. Then you should just use plugin-automd then you got it.

**Comment by bsuooo** [comment]
> After a little digg'in, I think this may caused by extracting plugin-automd out of preset-commonmark. You should just use plugin-automd then you got it. I think it's better to make plugin-automd shipped with crepe.

its works, thank you

**Comment by jh97uk** [comment]
For those wondering how to make this work in Crepe:
Run: `npm install @milkdown/plugin-automd`

Then the code you need is:

```javascript
import { automd } from "@milkdown/plugin-automd";
const crepe = new Crepe({
  root: "#editor",
  defaultValue: "Hello, Milkdown!",
});
crepe.editor.use(automd)
crepe.create()
```
