### ISSUE TITLE
[Bug] Repository tags don't match packages

### ISSUE THREAD

**Issue by seangwright** [Milkdown/milkdown#1569]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.5.7

### Steps to reproduce

If you look at the `package.json` of v7.5.7 of `@milkdown/crepe` on npm,  you can see it's [package.json](https://www.npmjs.com/package/@milkdown/crepe?activeTab=code) does not match the [package.json](https://github.com/Milkdown/milkdown/blob/%40milkdown/vue%407.5.0/packages/crepe/package.json) of the [package.json](https://github.com/Milkdown/milkdown/blob/%40milkdown/crepe%407.5.7/packages/crepe/package.json) for `@milkdown/crepe`.

The key issue for me is the exports of the package are different

**@milkdown/crepe 7.5.7 on npm**
```json
  "exports": {
    ".": {
      "import": "./lib/esm/index.js",
      "require": "./lib/cjs/index.js",
      "types": "./lib/types/index.d.ts"
    },
    "./theme/common/*": "./lib/theme/common/*",
    "./theme/classic.css": "./lib/theme/classic/style.css", <-- this line does not exist in repo -->
    "./theme/classic-dark.css": "./lib/theme/classic-dark/style.css",
    "./theme/nord.css": "./lib/theme/nord/style.css",
    "./theme/nord-dark.css": "./lib/theme/nord-dark/style.css",
    "./theme/frame.css": "./lib/theme/frame/style.css",
    "./theme/frame-dark.css": "./lib/theme/frame-dark/style.css"
  },
```

**@milkdown/crepe 7.5.0 on GitHub**
```json
  "exports": {
    ".": {
      "import": "./src/index.ts"
    },
    "./theme/common/*": "./src/theme/common/*",
    "./theme/crepe.css": "./src/theme/crepe/style.css", <-- this line does not exist on npm -->
    "./theme/crepe-dark.css": "./src/theme/crepe-dark/style.css",
    "./theme/nord.css": "./src/theme/nord/style.css",
    "./theme/nord-dark.css": "./src/theme/nord-dark/style.css",
    "./theme/frame.css": "./src/theme/frame/style.css",
    "./theme/frame-dark.css": "./src/theme/frame-dark/style.css"
  },
```

Additionally, [the docs for Crepe](https://milkdown.dev/docs/guide/using-crepe) state that the following themes are available
* `frame`
* `classic`
* `nord`
* `frame-dark`
* `classic-dark`
* `nord-dark`

Unfortunately, although the [crepe theme](https://www.npmjs.com/package/@milkdown/crepe?activeTab=code) exists in the npm package it is not exported. Instead the classic theme is exported even though it doesn't exist in the package.

The latest tag of the repo [has the correct export](https://github.com/Milkdown/milkdown/blob/%40milkdown/vue%407.5.0/packages/crepe/package.json#L23) but this tag hasn't been published to npm even though **it's a lower version than what's on npm**.

It seems like there are some problematic maintenance issues with this repo at the moment.

### Expected behavior

I can use the Crepe theme listed in the docs

### Actual behavior

I cannot use the Crepe theme listed in the docs because the package published on npm is broken.

### Runtime

Chrome

### OS

Windows

### Build and bundle tools

Webpack

**Comment by noozo** [comment]
+1

**Comment by Saul-Mirone** [comment]
It's not a issue, the files from `/lib` directory is built result and should only exists in release version.
