### ISSUE TITLE
[Bug] Table parse wrong

### ISSUE THREAD

**Issue by 4-1-1** [Milkdown/milkdown#595]
**Describe the bug**
```markdown
| a          | b                                                      | c       |
| :---------- | :------------------------------------------------------ | :------------------- |
| --          | --                                                      | --                   |
| 1 | --                                                      | 3 |
```

| a          | b                                                      | c       |
| :---------- | :------------------------------------------------------ | :------------------- |
| --          | --                                                      | --                   |
| 1 | --                                                      | 3 |

**To Reproduce**

**Expected behavior**
Parse table like github

**Screenshots**
<img width="496" alt="image" src="https://user-images.githubusercontent.com/4401981/177233887-1b22a718-3d13-4d40-93b3-edc0dccca14a.png">

**Milkdown version**
6.2.0

**Desktop (please complete the following information):**

-   OS: macOS
-   Browser chrome
-   Version 101

**Smartphone (please complete the following information):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**
Maybe  I should report to remark-gfm , not sure

**Comment by Saul-Mirone** [comment]
Yeah, that's a remark bug. I'll create a issue there.

**Comment by Saul-Mirone** [comment]
https://github.com/remarkjs/remark-gfm/issues/39

**Comment by Saul-Mirone** [comment]
https://github.com/micromark/micromark-extension-gfm-table/issues/7

**Comment by benatkin** [comment]
Marked as fixed upstream and Milkdown seems to be handling it like a boss now

<img width="1347" alt="Captura de pantalla 2024-06-03 a la(s) 7 35 52 p m" src="https://github.com/Milkdown/milkdown/assets/4126/fdec824e-6c02-45bd-9ace-1ede07731fe6">
