### ISSUE TITLE
[Bug] Mark inactive after entering a character

### ISSUE THREAD

**Issue by iHaPBoy** [Milkdown/milkdown#809]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

6.5.2

### Steps to reproduce

![inclusive](https://user-images.githubusercontent.com/2498173/201256217-63ddba53-db5b-4e92-b653-753587501c62.gif)

**Reference:** https://github.com/Saul-Mirone/milkdown/pull/695#discussion_r1019797143

### Expected behavior

multiple characters can be entered after toggle mark

### Actual behavior

mark inactive after entering a character

**Comment by Saul-Mirone** [comment]
Closing since we don't have menu plugin now.
