### ISSUE TITLE
[Planned] Milkdown V7

### ISSUE THREAD

**Issue by Saul-Mirone** [Milkdown/milkdown#817]
🔽 Sorted by priority:

- [x] #822 
- [x] #821 
- [x] #818 
- [x] #820 
- [x] #823

**Comment by gaminglifex** [comment]
will the latest version include codemirror like the one shown in official website? 
![image](https://user-images.githubusercontent.com/72642816/209898728-52d03714-39c8-43b8-b03e-300eb5c7570c.png)

**Comment by Saul-Mirone** [comment]
> will the latest version include codemirror like the one shown in official website? ![image](https://user-images.githubusercontent.com/72642816/209898728-52d03714-39c8-43b8-b03e-300eb5c7570c.png)

I think it's still not part of the editor core.

**Comment by aschojz** [comment]
@Saul-Mirone is there anywhere documented, how you did this? So I can build this on my own, even when it's not going to be in the core. Thanks a lot.

**Comment by Saul-Mirone** [comment]
> @Saul-Mirone is there anywhere documented, how you did this? So I can build this on my own, even when it's not going to be in the core. Thanks a lot.

The source code is at https://github.com/Saul-Mirone/milkdown/tree/v6/website/component/Demo

**Comment by enpitsuLin** [comment]
@gaminglifex That I just made a [plugin](https://github.com/enpitsuLin/milkdown-lab/tree/master/packages/plugin-split-editing) to show split edit view

**Comment by Saul-Mirone** [comment]
The milkdown V7 is released.
