### ISSUE TITLE
[RFC] Hybrid Editing

### ISSUE THREAD

**Issue by Saul-Mirone** [Milkdown/milkdown#819]
Add support for:

- [x] Hybrid mode for bold
- [x] Hybrid mode for italic
- [x] Hybrid mode for link
- [x] Hybrid mode for images

**Comment by iHaPBoy** [comment]
What is the implementation of supporting `HTML Tags`? Add some Input Rules to handle HTML Tags or add an HTML Node?

**Comment by Saul-Mirone** [comment]
> What is the implementation of supporting `HTML Tags`? Add some Input Rules to handle HTML Tags or add an HTML Node?

The user behavior of `HTML` is still being designed. I'll let you know when it's done.

**Comment by Saul-Mirone** [comment]
The HTML feature will be introduced later and is followed up in https://github.com/Milkdown/milkdown/issues/895.
Closing this one.

**Comment by Ainias** [comment]
Thanks for your awesome work, @Saul-Mirone ! 
Can you tell me how I can enable the hybrid mode? As I understand it, the hybrid mode should display the markdown syntax when the cursor is inside the element, correct?

**Comment by kajogo777** [comment]
any documentation on how to enable the hybrid mode? I've been looking for days
