### ISSUE TITLE
[Bug] **manager.set(ThemeIcon,** can not invoke mulity times

### ISSUE THREAD

**Issue by newproplus** [Milkdown/milkdown#865]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

6.5.4

### Steps to reproduce

```js
export const genI18nTheme = () => themeFactory((emotion, manager) => {
// ... other code
manager.set(ThemeIcon, (iconId) => {
    console.log('>>>>>>>>>>>> set ThemeIcon') // not execute
    if (!iconId) return

    const icon = getIcon(iconId)

    if (icon) {
      icon.label = t(icon.label)
    }

    return icon
  })
}
// ... other code
```

If editor has inited, I use **genI18nTheme()** as param to invoke Macro **switchTheme** after locale changed:
```js
editor.action(switchTheme(genI18nTheme()))
```

**console.log** inside does not work.

I also tested the flowing code, they works well
```
manager.set(ThemeColor
manager.set(ThemeSize
manager.set(ThemeFont
manager.set(ThemeScrollbar
manager.set(ThemeShadow
manager.set(ThemeBorder
```

### Expected behavior

make it works

### Actual behavior

not works

### Runtime

Other (please specify in steps to reproduce)

### OS

Windows

### Build and bundle tools

Vite

**Comment by Saul-Mirone** [comment]
Closing this one since `themeManager` has been removed since v7.
