### ISSUE TITLE
[Bug] Custom link node from example mixes up the letters when typing http://

### ISSUE THREAD

**Issue by sytolk** [Milkdown/milkdown#867]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

6.5.2

### Steps to reproduce

I have custom Link the same code from this sample: 
https://github.com/Saul-Mirone/milkdown/blob/main/examples/react/component/milkdown/index.tsx#L31

and when start typing http://www -> It mixes up the letters, and you can't even delete them from the keyboard.

![F53A9EC2-4178-48EB-9FB3-6174F92D9467](https://user-images.githubusercontent.com/1415463/211045600-16389077-a1da-4fcf-86e0-68df0644a7d9.png)

If I remove custom Link this issue not exist

### Expected behavior

typing http://www.google.com in milkdown editor

### Actual behavior

typing only http://w and the cursor stay behind the last character of the url

**Comment by Saul-Mirone** [comment]
I think the problem will be resolved by v7.

**Comment by Saul-Mirone** [comment]
Fixed, closing this one, thanks for your report.

**Comment by Saul-Mirone** [comment]
The mark view component is deprected because it's not recommended by the author of prosemirror, see more: https://discuss.prosemirror.net/t/prosemirror-adapter-for-react-and-vue/5010/2

So the recommended way is to use widgets decorators. like how I implemented it in playground: https://github.com/Milkdown/website/blob/main/src/components/playground-editor/editor-component/LinkWidget.tsx

**Comment by Saul-Mirone** [comment]
You need to use both gfm plugin and commonmark plugin.

**Comment by sytolk** [comment]
@Saul-Mirone with milkdown v7 can I add onClick to linkAttr? Now link schema have only href and title attributes:
https://github.com/Milkdown/milkdown/blob/main/packages/preset-commonmark/src/mark/link.ts#L19

**Comment by knownasilya** [comment]
@sytolk did you figure it out?

**Comment by sytolk** [comment]
@knownasilya yes I have fix this with milkdown v7 using [handleClickOn](https://prosemirror.net/docs/ref/#view.EditorProps.handleClickOn) look at:
https://github.com/tagspaces/tagspaces-common/blob/milkdown-v7/packages/tagspaces-md/src/EditorContext/EditorContextProvider.tsx#L145

**Comment by knownasilya** [comment]
@sytolk found a bug in that if you have multiple links in a paragraph this only opens the first one no matter which one you click. Here's something that worked for me.

```typescript
const handleClick = (ctx, view: EditorView, pos: number) => {
  const found = view.state.tr.doc.nodeAt(pos);

  if (found && found.marks.length > 0) {
    const mark = found.marks.find(m => m.type.name === 'link');
    const href = mark?.attrs.href;
    let path: string;

    if (hasURLProtocol(href)) {
      path = href;
    } else {
      path = encodeURIComponent(href);
    }

    window.open(path, '_blank');
  }
  return true;
};
```

Also I think the observer needs to be cleaned up on editor unmount.

**Comment by sytolk** [comment]
@knownasilya I can't repeat this bug. Here I use [findChildrenByMark](https://github.com/Milkdown/milkdown/blob/main/packages/prose/src/toolkit/prose/node.ts#L24) here https://github.com/tagspaces/tagspaces-common/blob/milkdown-v7/packages/tagspaces-md/src/EditorContext/EditorContextProvider.tsx#L104
and the first parameter on this function receive node that is clicked on from handleClick. Can you create [StackBlitz](https://stackblitz.com/github/Milkdown/examples/tree/main/react-commonmark) to repeat this issue? 
Thanks!
