### ISSUE TITLE
[Bug] Can't Indent Bullet Point When Tabbing

### ISSUE THREAD

**Issue by tengkuizdihar** [Milkdown/milkdown#897]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

^6.5.4

### Link to runnable example

https://codesandbox.io/s/affectionate-firefly-17ruh4?file=/src/App.js

### Steps to reproduce

Use this https://codesandbox.io/s/affectionate-firefly-17ruh4?file=/src/App.js

### Expected behavior

When tabbing, the bullet point would go "inwards" like when you're using the playground https://milkdown.dev/playground

### Actual behavior

It doesn't

### Runtime

Chrome

### OS

Linux

### Build and bundle tools

Vite

**Comment by Saul-Mirone** [comment]
In milkdown v6, the shortcut is `Mod-[` and `Mod-]`. I just changed it to `tab` in v7.

**Comment by Saul-Mirone** [comment]
BTW, if you're new to milkdown, I highly recommend you to start with v7. For now you need to install it with `@next` label, but it will be released with in this month.
