### ISSUE TITLE
[Bug] missing underline action

### ISSUE THREAD

**Issue by DaSchTour** [Milkdown/milkdown#914]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.0.0

### Steps to reproduce

In playground use the underline action which actually does a strike-through

### Expected behavior

There should be an underline action in commonmark or gfm

### Actual behavior

There is no action preset for underline

**Comment by Saul-Mirone** [comment]
Underline is not part of the commonmark or GFM spec.
