### ISSUE TITLE
[Feature] Support Math Block WYSIWYG using mathlive

### ISSUE THREAD

**Issue by 66Leo66** [Milkdown/milkdown#917]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

Currently Math Block cannot be edited WYSIWYG like other content types.

### Solution

Use [mathlive](https://cortexjs.io/mathlive/)

Mathlive demo [here](https://cortexjs.io/mathlive/demo/)

### Alternatives

Maybe MathQuill?

**Comment by Saul-Mirone** [comment]
You can create a community plugin to integrate mathlive or mathquill. In the official plugin we want to keep it primitive. Implementing an editable math block won't be difficult like what we did in online playground.
