### ISSUE TITLE
[Bug] `inlineSyncPlugin` triggers `markdownUpdated` event

### ISSUE THREAD

**Issue by ylc395** [Milkdown/milkdown#923]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.1.0

### Steps to reproduce

1. use `listener` & `commonmark` plugins
2. listen to `markdownUpdated` event
3. paste an image into editor
4. `markdownUpdated` event was triggered extra twice. 

<img width="240" alt="image" src="https://user-images.githubusercontent.com/12264626/223626707-bf6578e1-624c-46ad-a3d4-1986b57f6dc8.png">

### Expected behavior

`inlineSyncPlugin` doesn't trigger any event since it's an internal mechanism.

### Actual behavior

`markdownUpdated` event was triggered extra twice. 

### Runtime

Electron

**Comment by ylc395** [comment]
I found another problem caused by inlineSyncPlugin maybe:

1. define and use a `$nodeSchema`(`multimedia` node)
2. define and use a corresponding `$view`(`multimedia` node view)
3. use a custom uploader for `@milkdown/plugin-upload`:
```ts
  async uploader(files, schema) {
    // some async business log to upload files and get therir id on Server
    // ...(omit)
    // ...
    // create and return multimedia node here, with `mimeType` attr
    // ** make multimedia node view constructor invoked with `mimeType` attr**, excepted
    return updatedFiles.map((file) => {
      const node = multimediaNode.createAndFill({
        src: `${fileProtocol}:///${file.id}`,
        alt: file.name,
        mimeType: file.mimeType,
      });

      if (!node) {
        throw new Error('create node failed');
      }

      return node;
    });
  },
```
4. node view constructor invoked again unexpectedly, losing `mimeType` attr. Here is call stack: 

<img width="632" alt="image" src="https://user-images.githubusercontent.com/12264626/224644702-e378ee85-146c-4d1e-8380-02a8861d29d4.png">


Is inlineSyncPlugin breaking ProseMirror's diff algorithm or something, which cause the multimedia is re-created by markdown text? (`![](file.id)`)

**Comment by Saul-Mirone** [comment]
It's caused by your node schema doesn't serialize to markdown correctly. I still think instead of creating a new node. You should extend the image schema if you just want to change the behavior of `toDOM` and `parseDOM`, like what I did in [task list item](https://github.com/Milkdown/milkdown/blob/main/packages/preset-gfm/src/node/task-list-item.ts).

**Comment by ylc395** [comment]
Ok, choosing the proper plan for features is case-depending, but how about this:

https://github.com/Milkdown/milkdown/blob/74409b93b692df3bf881b2e4644711e3d954b409/packages/preset-commonmark/src/plugin/inline-sync-plugin/context.ts#L97

Should we copy all attrs of all descendants here, instead of the most outer node?

**Comment by Saul-Mirone** [comment]
> 

It's by design because after the syncing happens, we don't know what exactly happened inside the paragraph or heading node (based on the preset). So we just let the markdown parser _take over_ the job and give us the right result.
