### ISSUE TITLE
[Bug] Context "list_item" not found, do you forget to inject it?

### ISSUE THREAD

**Issue by knownasilya** [Milkdown/milkdown#927]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

preset-gfm 7.1.0, others same version

### Steps to reproduce

```ts
const editor = Editor.make()
    .config((ctx) => {
      ctx.set(rootCtx, element);

      if (content !== undefined) {
        ctx.set(defaultValueCtx, content);
      }
 })
    .use(nord as any)
    .use(gfm);

editor.create().then(() => {
    debugger;
  });
```

Using arc browser, but I don't think this is browser dependent. I'm using this in Ember.js, which uses some webpack and other custom things under the hood.

### Expected behavior

Editor to show up

### Actual behavior

I get this error

```
index.es.js:25 Uncaught (in promise) MilkdownError: Context "list_item" not found, do you forget to inject it?
    at f (index.es.js:25:1333)
    at b.eval [as get] (index.es.js:14:810)
    at P.eval [as use] (index.es.js:14:2100)
    at P.eval [as get] (index.es.js:14:2129)
    at eval (index.es.js:44:8327)
    at eval (index.es.js:68:10853)
    at Array.map (<anonymous>)
    at Ce.eval [as create] (index.es.js:68:10789)
    at Object.editor [as instance] (editor.js:74:1)
```

### Runtime

Other (please specify in steps to reproduce)

### OS

macOS

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by Saul-Mirone** [comment]
Use commonmark together with gfm, it's by design.

**Comment by knownasilya** [comment]
Should the docs reflect this? Which one comes first in plugin order or does that not matter?

**Comment by Saul-Mirone** [comment]
The commonmark preset should come first, I've updated the api document.

**Comment by ShravanSunder** [comment]
ran into the same issue, i think the docs should reflect this.  maybe a troublehsooting section?  I can make a PR if that's alright

**Comment by Saul-Mirone** [comment]
> Ran into the same issue, i think the docs should reflect this (it almost stopped me from using this library). maybe a troublehsooting section? I can make a PR if that's alright @Saul-Mirone

We have an FAQ section in doc, feel free to add content for it.
