### ISSUE TITLE
[Bug]Collaborative plugin was not properly uninstalled

### ISSUE THREAD

**Issue by z-950** [Milkdown/milkdown#935]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

6.x and 7.x

### Steps to reproduce

If reconnect `collabService`, `doc` in `ySyncPlugin` not the latest one. Which make `yCursorPlugin` broken.
Because [`disconnect`](https://github.com/Milkdown/milkdown/blob/6919ff0c4f8742244deff8468164bf944da32b45/packages/plugin-collab/src/collab-service.ts#L218) just do nothing in real. So that the internal initialization function was not called when the plugin was recreated.

1. create a `doc`, set default template and connect room A.
2. disconnect room A.
3. create a `doc`, set different default template and connect room B.
4. yCursorPlugin is broken.

### Expected behavior

Collab plugins should be really uninstall.

### Actual behavior

Collab plugins are not really uninstall.

### Runtime

Chrome

### OS

Windows

**Comment by Saul-Mirone** [comment]
I don't really understand the reason. The `doc` is a `yDoc`, if the reconnection happens, it should know how to update itself when receiving new transactions. What's the behavior it cause?

**Comment by z-950** [comment]
Oh, it is something about switching room.
The only way I know is to disconnect current room and connect a new one.
And they are about different content.

So `doc` should be create for the new content, not be update.

**Comment by Saul-Mirone** [comment]
Have you took a look at [this example](https://github.com/Milkdown/examples/tree/main/vanilla-collab)? I think you need to bind new doc when switching rooms.
