### ISSUE TITLE
[Bug]  error  Unable to resolve path to module '@milkdown/theme-nord/style.css'

### ISSUE THREAD

**Issue by PungYoung** [Milkdown/milkdown#937]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

 "@milkdown/theme-nord": "^7.1.0"

### Steps to reproduce

```vue
<script setup lang="ts">
  import '@milkdown/theme-nord/style.css';
  import './style.css';
  import { MilkdownProvider } from '@milkdown/vue';
  import { ProsemirrorAdapterProvider } from '@prosemirror-adapter/vue';
  import Milkdown from './MilkdownEditor.vue';
</script>

<template>
  <MilkdownProvider>
    <ProsemirrorAdapterProvider>
      <Milkdown />
    </ProsemirrorAdapterProvider>
  </MilkdownProvider>
</template>
```

### Expected behavior

Load css normally

### Actual behavior

Unable to load css normally

### Runtime

Chrome

### OS

Windows

### Build and bundle tools

Vite

**Comment by PungYoung** [comment]
clone  https://github.com/Milkdown/examples/tree/main/vue-custom-component  is normal and strange

**Comment by Saul-Mirone** [comment]
Cannot reproduce.

**Comment by PungYoung** [comment]
I customized a theme, which looks OK.

**Comment by mrsai** [comment]
确切的说，不是不能引入这个样式，是缺少了一些样式定义，我也遇到了这个问题。
如果你按照vue的文档说明，并不能明确的知道这丢失的一部分样式从哪里引入。
比如包含 .prose :where(h1):not(:where([class~="not-prose"] *)) 这一句，我在整个@milkdown中都没有找到。
后来我看了Demo，才知道编辑器样式其实和tailwindcss强制绑定了，
但是我没有理解作者为什么没有把tailwindcss那一部分代码也抽取出来。但如果你想保持一致，可以也引入这个css处理器，
或者你直接把demo生成的样式copy到自己的项目。

**Comment by ningkehua** [comment]
> 

"你直接把demo生成的样式copy到自己的项目"
