### ISSUE TITLE
[Bug] When I change the editable value, the editor doesn't inject some plugins 

### ISSUE THREAD

**Issue by zgrybus** [Milkdown/milkdown#946]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.1.0

### Link to runnable example

https://codesandbox.io/s/smoosh-sunset-ey4uhy?file=/src/MathView.tsx

### Steps to reproduce

- Go to https://codesandbox.io/s/smoosh-sunset-ey4uhy?file=/src/MathView.tsx
- Toggle the editable prop by clicking on the button

### Expected behavior

I can easily change the value of **editable**

### Actual behavior

Page breaks and I'm getting 
```typescript
Context "katexOptions" not found, do you forget to inject it?
```

### Runtime

Chrome, Safari, Firefox

### OS

Windows, Linux, macOS

### Build and bundle tools

Vite

**Comment by Saul-Mirone** [comment]
You're recreating the editor when toggling the readonly mode and if you inspect the editor status before call the katex render method. You'll find it is `destroyed`. The general solution are either not to recreate the editor when toggling readonly mode or put your logic in useEffect into a `requestAnimationFrame`

**Comment by zgrybus** [comment]
@Saul-Mirone Thanks, it worked with `requestAnimationFrame`. 
If someone is curios, there is a solution for updating `editable` value.

```typescript
  useEffect(() => {
    const effect = async () => {
      const editor = getEditor();

      if (loading || !editor) {
        return;
      }

      editor.use(
        [
          (ctx: Ctx) => () => {
            ctx.update(editorViewOptionsCtx, (prev) => ({
              ...prev,
              editable: () => editable
            }));
          }
        ].flat()
      );

      await editor.create();
    };

    requestAnimationFrame(() => {
      effect();
    });
  }, [loading, getEditor, editable]);
```
