### ISSUE TITLE
[Bug] Slash command popover selection regresssion

### ISSUE THREAD

**Issue by echarles** [Milkdown/milkdown#947]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest

### Steps to reproduce

The slash command is showing regressions. When you invoke `/`, the popover meny should be selected with your arrow up/down keystrokes. You have now to use your mouse to select an menu entry.

Also, when you have selected that entry, the cursor is not positioning at the correct place.

![Untitled6](https://user-images.githubusercontent.com/226720/227219382-4244f833-7fcb-40d7-b5c0-f4832d86cdf3.gif)

### Expected behavior

The previous for the popover menu should be kept.

### Actual behavior

The mouse is needed.

### OS

Linux

**Comment by syntaxbullet** [comment]
I am not sure if i understand this correctly, but as far as I know milkdown version 7 and probably all versions after v7 are headless, meaning when using the `plugin-slash` you probably built the dropdown component yourself? If this is true, it is your responsibility to make sure that when it opens, the first item inside of it is being focused, and to trap the focus inside of the element respectively.

**Comment by echarles** [comment]
The screenshot is the one taken from the playground https://milkdown.dev/playground

**Comment by Saul-Mirone** [comment]
That's just a really simple example provided in documentation website. You can help to improve it if you have interests.
