### ISSUE TITLE
block-plugin中菜单选项位置错误[Bug]

### ISSUE THREAD

**Issue by tinuv** [Milkdown/milkdown#959]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.1.0

### Link to runnable example

https://stackblitz.com/edit/github-3w8cea?file=components%2FEditor.tsx

### Steps to reproduce

见上面
![](https://renwuzhi.wiki/images/18.png)

### Expected behavior

菜单图表显示在正确的位置上

### Actual behavior

菜单显示在了错误的位置上

### Runtime

Chrome

### OS

macOS

### Build and bundle tools

Vite

**Comment by Saul-Mirone** [comment]
Remove the padding of list or use a custom list item component.
