### ISSUE TITLE
[Bug] emoji picker not showing

### ISSUE THREAD

**Issue by knownasilya** [Milkdown/milkdown#962]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

v7

### Link to runnable example

See the playground

### Steps to reproduce

See the playground

### Expected behavior

Should open emoji picker after typing `:...`

### Actual behavior

Nothing happens.

**Comment by Saul-Mirone** [comment]
We don't provide emoji picker now. You can use slash plugin to build one yourself.
