### ISSUE TITLE
[Bug] When multiple editors are being used, commands are always applied on the last created

### ISSUE THREAD

**Issue by groege** [Milkdown/milkdown#974]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

@milkdown/core 7.2.0

### Steps to reproduce

Create two Milkdown editors in one page, call a command (ie toogle bold,...)
The command will be applied to the last created editor

### Expected behavior

Command should be applied to the editor it has been called on...

If I understood the code correctly, the problem lies within "commands.ts" 

this way we only have one command manager instance, no matter how many editors we create
`export const commandsCtx = createSlice(new CommandManager(), 'commands')`

when the plugin will be loaded, the context will be overwritten so all editors will only have the last instance set...
```
export const commands: MilkdownPlugin = (ctx) => {
  ctx.inject(commandsCtx).inject(commandsTimerCtx).record(CommandsReady)
  ctx.get(commandsCtx).setCtx(ctx)
  return async () => {
    await ctx.waitTimers(commandsTimerCtx)

    ctx.done(CommandsReady)

    return () => {
      ctx.remove(commandsCtx).remove(commandsTimerCtx).clearTimer(CommandsReady)
    }
  }
}```

**Comment by Saul-Mirone** [comment]
Which framework do you use it with?

**Comment by groege** [comment]
> Which framework do you use it with?

plain javascript (no react,...)

**Comment by groege** [comment]
> Make sense, will fix it soon.

thanks :)

**Comment by zgrybus** [comment]
@groege 
Has your problem been fixed? After repair, no method can be used :/

**Comment by matzedav** [comment]
Are there any plans on merging this into the main branch? I have four editor instances and on any commands its inserted into the last created editor.
