### ISSUE TITLE
[Feature] Disable twemoji

### ISSUE THREAD

**Issue by v1r0x** [Milkdown/milkdown#982]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

I want to use and keep unicode emojis instead of fetching emojis/images from an external source (twemoji).

### Solution

Easiest solution would be to allow disabling twemoji in `emojiConfig`.

### Alternatives

Currently I overwrite `twemojiOptions` in `emojiConfig` to change the base url to a (nonexisting) local url to prevent the plugin from fetching those images.

**Comment by Saul-Mirone** [comment]
Just remove plugins you don't want herer:
https://github.com/Milkdown/milkdown/blob/main/packages/plugin-emoji/src/index.ts#L131

**Comment by v1r0x** [comment]
I already tried to not import `remarkTwemojiPlugin`, but that didn't help.
Also removing `insertEmojiInputRule` fixed it!

**Comment by Saul-Mirone** [comment]
Just tried, removing `remarkTwemojiPlugin` can use the system emoji.
