### ISSUE TITLE
[Bug] ResolvedPos doesn't contain proper types

### ISSUE THREAD

**Issue by NayamAmarshe** [Milkdown/milkdown#986]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.2.1

### Link to runnable example

https://github.com/NayamAmarshe/writedown/pull/56/files

### Steps to reproduce

```typescript
const codeBlockKeymap = $shortcut((ctx): Keymap => {
    return {
      Backspace: (state, dispatch) => {
        const { selection } = state;
        const { $from } = selection;

        if (
          !$from["path"][3] ||
          $from["path"][3].type.name !== "code_block" ||
          $from.pos !== 1
        )
          return false;

        return true;
      },
    };
  });
```

### Expected behavior

`$from` (ResolvedPos) should contain properties like `path`.
![image](https://user-images.githubusercontent.com/25067102/233850489-ac6a5451-3133-413b-81a8-89df556f4b83.png)

### Actual behavior

ResolvedPos does not match the output we get in console. No such property exists in the types but it should.  

`Element implicitly has an 'any' type because expression of type '"path"' can't be used to index type 'ResolvedPos'. Property 'path' does not exist on type 'ResolvedPos'.ts(7053)`
![image](https://user-images.githubusercontent.com/25067102/233850456-6e743944-d7a4-447c-b2c3-e8f2bb22a42b.png)

### Runtime

Chrome

### OS

Linux

### Build and bundle tools

Next.js

**Comment by Saul-Mirone** [comment]
This seems a prosemirror bug, please open in their repo.

**Comment by NayamAmarshe** [comment]
> This seems a prosemirror bug, please open in their repo.

Ah ok. Didn't realize, sorry.
