### ISSUE TITLE
[Bug] emphasis input behaver

### ISSUE THREAD

**Issue by s524797336** [Milkdown/milkdown#989]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.2.1

### Steps to reproduce

![20230502-142614](https://user-images.githubusercontent.com/10988202/235594256-bae01803-8675-4cae-99b0-4ec52298f000.gif)

### Expected behavior

Add emphasis mark to selected text

### Actual behavior

Add \_ to text

### Runtime

Chrome

### OS

macOS

### Build and bundle tools

esbuild

**Comment by Saul-Mirone** [comment]
The behavior is by design, che_ck th_e is not a valid emphasis string in commonmark.

**Comment by s524797336** [comment]
![20230502-221424](https://user-images.githubusercontent.com/10988202/235693129-cc81a61a-a5a6-4e67-9ea8-4e6709e36120.gif)
![20230502-221732](https://user-images.githubusercontent.com/10988202/235693917-a67face8-b8e8-4efd-8992-827f33a0816d.gif)
How about this two?

**Comment by Saul-Mirone** [comment]
Duplicated with https://github.com/Milkdown/milkdown/issues/956#issuecomment-1493657219

**Comment by s524797336** [comment]
@Saul-Mirone With the milkdown playground, how to add emphasis to text? The emphasis button event break the history plugin.
