### ISSUE TITLE
[Bug] Markdown Code-Block not exported correctly

### ISSUE THREAD

**Issue by rbeier** [Milkdown/milkdown#994]
Hi,

i think the commonmark plugin doesn't export correct markdown syntax. 
Maybe there is a way to configure the commonmark plugin as stated [here](https://milkdown.dev/docs/api/preset-commonmark#code-block). If yes, please post an example. Thank you!

### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.1.1

### Link to runnable example

https://stackblitz.com/edit/github-a347ca?file=components/Editor.tsx

### Steps to reproduce

1. open stackblitz
2. open console
3. write something into the editor to trigger the markdownUpdated method

### Expected behavior

the code block in the console output of the `markdownUpdated` method should be wrapped in three backticks (`) 

if you specify the syntax of the code block (```js) it works as expected

### Actual behavior

the code block is indented by four spaces.

### Runtime

Chrome

### OS

macOS

### Build and bundle tools

Vite

**Comment by Saul-Mirone** [comment]
It's generated automatically by remark, you may want to look at https://github.com/remarkjs/remark/tree/main/packages/remark-stringify#optionsfences

**Comment by rbeier** [comment]
Thanks for your quick response! Worked as expected :)

Solution is to change remarkStringifyOptionsCtx:

```js
ctx.set(remarkStringifyOptionsCtx, {
    fences: true
});
```
