### ISSUE TITLE
[Feature] Drawing Block

### ISSUE THREAD

**Issue by Novout** [Milkdown/milkdown#995]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Problem

I'm using milkdown in a project for notes/drafts, and there is no specific block to draw. It's something that can be done by building an external plugin, but I think it's interesting to have this natively.

### Solution

From an input sequence, a block would be inserted, which will listen for touch/mouse and change the appearance of the block.

### Alternatives

- Plugin integration (plugin-drauu, using [Drauu](https://github.com/antfu/drauu), for example).

**Comment by Saul-Mirone** [comment]
I don't have a plan to add it as an official plugin. You can create a community plugin like https://github.com/enpitsuLin/milkdown-lab if you want.
